[.nxsl-function]
[[func-bindobject]]
== BindObject()

NOTE: Deprecated since 3.0, use <<class-netobj-bind>> or <<class-netobj-bindto>> instead.

NOTE: This function is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

[source,c]
----
BindObject(parent, child) => void
----

Bind all NetXMS objects that can be bound from console (nodes, subnets, clusters, and another containers) to container objects.

.Parameters
[cols="1,3" grid="none", frame="none"]
|===
|parent|Parent object (<<class-netobj>> referring to container object or infrastructure service root).
|child|The NetXMS object to be linked to given parent object (<<class-node>> or <<class-netobj>> referring to subnet, container, or cluster).
|===

.Return
None.

.Example
[.source]
....
BindObject(FindObject(2), $node);    // Link current node directly to "Infrastructure Services"
BindObject(FindObject("Services"), FindObject("Service_1"));    // Link object named "Service_1" to container "Services"
....
