[[func-bindobject]]
== BindObject()

****
[IMPORTANT]
====
*This function is deprecated. Starting form version 3.0.* 
Please use bind and bindTo functions in <<class-netobj>>. 
====
****

[source,c]
----
BindObject(parent, child) => void
----

Bind all NetXMS objects that can be bound from console (nodes, subnets, clusters, and another containers) to container objects.
This function can be disabled in server configuration file by "NXSL.EnableContainerFunctions" server configuration parameter.

.Parameters
[cols="1,3" grid="none", frame="none"]
|===
|parent|Parent object (<<class-netobj>> referring to container object or infrastructure service root).
|child|The NetXMS object to be linked to given parent object (<<class-node>> or <<class-netobj>> referring to subnet, container, or cluster).
|===

.Return
None.

.Example
[.output]
....
BindObject(FindObject(2), $node);    // Link current node directly to "Infrastructure Services"
BindObject(FindObject("Services"), FindObject("Service_1"));    // Link object named "Service_1" to container "Services"
....
