[[class-interface]]
=== Interface

Represent interface object. Inherit all attributes and methods of the <<class-netobj>> class.

==== Instance attributes

`adminState`::
Administrative <<enum-interface-state,state>> of the interface.

`alias`::
Interface alias (usually value of SNMP ifAlias).

`bridgePortNumber`::
Bridge port number for this interface.

`description`::
Interface description

`dot1xPaeAuthState`::
802.1x PAE authentication state

`dot1xBackendAuthState`::
802.1x back-end authentication state

`expectedState`::
<<enum-interface-expected-state,Expected state>> of the interface.

`flags`
Interface flags (bit mask, `uint32`).

`ifIndex`::
Interface index.

`ifType`::
Interface type

`isExcludedFromTopology`::
`TRUE` if this interface excluded from network topology

`isLoopback`::
`TRUE` if this interface is a loopback

`isManuallyCreated`::
`TRUE` if this interface object was created manually by NetXMS administrator

`isPhysicalPort`::
`TRUE` if this interface object represents physical port

`ipNetMask`::
IP network mask (number of bits).

`macAddr`::
String representation of MAC address separated by ":".

`mtu`::
Interface MTU (0 if unknown).

`node`::
Parent node object

`operState`::
Operational <<enum-interface-state,state>>.

`peerInterface`::
Peer interface object if known, otherwise `null`.

`peerNode`::
Peer <<class-node,node object>> if known, otherwise `null`.

`port`::
Port number.

`slot`::
Slot number.

`speed`::
Speed of the interface.

`zone`::
<<class-zone>> object (null if zoning is disabled).

`zoneId`::
Zone ID (0 if zoning is disabled)

[[enum-interface-state]]
.Interface states
|===
| Code | Description

| 0
| Unknown

| 1
| Up

| 2
| Down

| 3
| Testing

|===

[[enum-interface-expected-state]]
.Interface expected states
|===
| Code | Description

| 0
| Up

| 1
| Down

| 2
| Ignore

|===
