[[func-group-snmp]]
=== SNMP

[[func-CreateSNMPTransport]]
==== CreateSNMPTransport(`node`)

Create <<class-SNMP_Transport>> object in context of <<class-node>>.
Return `null` if transport cannot be created.

.Example
----
>>> transport = CreateSNMPTransport(FindObject("Server1"))
>>> print transport->snmpVersion
2c
----

[[func-SNMPGet]]
==== SNMPGet(`transport`, `oid`)

Perform SNMP GET request for `oid` over provided <<class-SNMP_Transport,transport>>. Return <<class-SNMP_VarBind>> or `null` on failure.

.Example
----
transport = CreateSNMPTransport(FindObject("Server1"));
if (transport != null) {
  oid = ".1.3.6.1.2.1.25.1.6.0"; // number of running processes
  varbind = SNMPGet(transport, oid);
  if (varbind != null) {
    trace(1, varbind->name . "=" . varbind->value);
  }
  else {
    trace(0, "SNMPGet() failed");
  }
}
----

==== SNMPGetValue(`transport`, `oid`)

Perform SNMP GET request for `oid` over provided <<class-SNMP_Transport,transport>>. Return `string` value of the result or `null` on failure.

This function is a wrapper for <<func-SNMPGet>>.

.Example
----
transport = CreateSNMPTransport(FindObject("Server1"));
if (transport != null) {
  oid = ".1.3.6.1.2.1.25.1.6.0"; // number of running processes
  value = SNMPGetValue(transport, oid);
  if (value != null) {
    trace(1, value);
  }
  else {
    trace(0, "SNMPGetValue() failed");
  }
}
----

==== SNMPSet(`transport`, `oid`, `value`, `dataType`)

Perform SNMP SET request for `oid` over provided <<class-SNMP_Transport,transport>>. Return boolean success indicator.
`value` is automatically converted from string based in `dataType`. If `dataType` is not provided, default type "STRING" will be used.

.Example
----
if (!SNMPSet(transport, oid, "192.168.0.1", "IPADDR") {
  trace(1, "SNMPSet failed");
}
----

.Data Types
|===
| Name | Description
| INTEGER | Integer.
| INT | Same as INTEGER.
| STRING | Octet string.
| OID | Object id.
| IPADDR | IP address.
| IP ADDRESS | Same as IPADDR.
| COUNTER32 | 32-bit counter.
| GAUGE32 | 32-bit unsigned integer.
| TIMETICKS | Timeticks.
| COUNTER64 | 64-bit counter.
| UINTEGER32 | 32-bit unsigned integer.
| UINT32 | Same as UINTEGER32.
|===

==== SNMPWalk(`transport`, `oid`)

Perform SNMP WALK request for `oid` over provided <<class-SNMP_Transport,transport>> and return collected values as array of <<class-SNMP_VarBind>> or `null` on failure.

.Example
----
transport = CreateSNMPTransport(FindObject("Server1"));
if (transport != null)
  oid = ".1.3.6.1.2.1.25.4.2.1.2"; // Names of the running processes
  vars = SNMPWalk(transport, oid);
  if (vars != null) {
    foreach (v: vars) {
      trace(1, v->name."=".v->value);
    }
  }
}
----
