// Shared NetObj attributes - include in classes that extend NetObj
// Usage: include::_shared/netobj-attrs.adoc[]

.Inherited from NetObj
[%collapsible]
====
`alarms => array`::
List of active <<class-alarm, Alarms>> for this object.

`alarmStats => array`::
Integer array that consists of 5 numbers - each number represents number of alarms for this and child objects for each of severity.

`alias: <<class-string,String>>`::
Object alias. For interfaces it is automatically collected on configuration poll (e.g. from SNMP ifAlias).

`asset => <<class-asset>>`::
Reference to <<class-asset,asset class>> of asset linked to this object.

`assetId: int`::
Id of linked asset object.

`assetProperties => <<class-assetproperties>>`::
Reference to <<class-assetproperties,asset properties class>> of asset linked to this object.

`backupZoneProxy => Node`::
Currently selected backup <<class-node,zone proxy>> (`null` if zoning is disabled or backup proxy is not assigned)

`backupZoneProxyId: int`::
ID of currently selected backup zone proxy (`0` if zoning is disabled or backup proxy is not assigned)

`category: <<class-string,String>>`::
Object's category name

`categoryId: int`::
Object's category ID

`children => array`::
List of child objects. Use <<func-classof>> to differentiate.

`city: <<class-string,String>>`::
Postal address - city.

`comments: <<class-string,String>>`::
Object comments.

`country: <<class-string,String>>`::
Postal address - country.

`creationTime: int64`::
Object creation time as UNIX timestamp

`customAttributes => HashMap`::
Hash map of object custom attributes.

`district: <<class-string,String>>`::
Postal address - district.

`geolocation => GeoLocation`::
Object <<class-geolocation,geographical location>>.

`guid: <<class-string,String>>`::
Object GUID as `string`.

`id: int`::
Unique object identifier.

`ipAddr: <<class-string,String>>`::
Primary IP address. Deprecated and will be removed in a future version, use `ipAddress` instead.

`ipAddress => InetAddress`::
+
[.version-added]
Added in version 5.1
+
Primary <<class-inetaddress,IP address>>.

`isInMaintenanceMode: bool`::
Maintenance mode indicator (`true` if object currently is in maintenace mode).

`maintenanceInitiator: int`::
Maintenance initiator user id

`mapImage: <<class-string,String>>`::
GUID of object image used for representation on the maps.

`name: <<class-string,String>>`::
Object name.

`nameOnMap: <<class-string,String>>`::
Object name displayed on map.

`parents => array`::
List of direct parents for this object (most likely either <<class-container>> or <<class-cluster>>).

`postcode: <<class-string,String>>`::
Postal address - postal code.

`primaryZoneProxy => Node`::
currently selected primary <<class-node,zone proxy>> (`null` if zoning is disabled or primary proxy is not assigned)

`primaryZoneProxyId: int`::
ID of currently selected primary zone proxy (`0` if zoning is disabled or primary proxy is not assigned)

`region: <<class-string,String>>`::
Postal address - region.

`responsibleUsers : <<class-array,Array>>`::
Array with user objects that are added as responsible users for this object. Objects are <<class-user>> or <<class-usergroup>>

`state: int`::
Current object state. One of: <<const-node-state>>, <<const-cluster-state>>, <<const-sensor-state>>

`status: int`::
Current <<const-object-status,object status>>.

`streetAddress: <<class-string,String>>`::
Postal address - street.

`type: int`::
<<enum-object-type,Object type>>.
====
