// Shared NetObj methods - include in classes that extend NetObj
// Usage: include::_shared/netobj-methods.adoc[]

.Inherited methods from NetObj
[%collapsible]
====
`bind(childObject) => void`::
Bind `childObject` to the current object as a child.

`bindTo(parentObject) => void`::
Bind current object to `parentObject` as a child.

`calculateDowntime(tag, periodStart, periodEnd): <<class-array,Array>>`::
Calculate node downtime. Returns array of <<class-downtimeinfo>> objects.

`clearGeoLocation() => void`::
Clears GeoLocation data from the node.

`createUserAgentNotification(message, startTime, endTime, showOnStartup): int`::
Send user agent notification. Returns message id.

`delete() => void`::
Deletes current object.

`deleteCustomAttribute(name) => void`::
Delete custom attribute.

`enterMaintenance() => void`::
Enable maintenance mode for the object.

`expandString(string): <<class-string,String>>`::
Expand string by replacing macros with their values.

`getCustomAttribute(name): <<class-string,String>>`::
Returns value of the custom attribute with the provided name.

`getResponsibleUsers(tag) => array`::
Returns list of responsible users with specific tag.

`isChild(object): bool`::
Returns TRUE if provided object is child of this object.

`isDirectChild(object): bool`::
Returns TRUE if provided object is direct child of this object.

`isDirectParent(object): bool`::
Returns TRUE if provided object is direct parent of this object.

`isParent(object): bool`::
Returns TRUE if provided object is parent of this object.

`leaveMaintenance() => void`::
Disable maintenance mode for the object.

`manage() => void`::
Sets object to managed state.

`readMaintenanceJournal(startTime, endTime): <<class-array,Array>>`::
Read maintenance entries. Returns array of <<class-maintenancejournalrecord>> objects.

`rename(name) => void`::
Rename object.

`setAlias(name) => void`::
Set object alias name.

`setCategory(idOrName) => void`::
Set object category id or name.

`setComments(comment, [isMarkdown]) => void`::
Set object comments.

`setCustomAttribute(key, value, inherit=false) => void`::
Update or create custom attribute.

`setGeoLocation(newLocation) => void`::
Sets node geographical <<class-geolocation,location>>.

`setMapImage(image) => void`::
Sets object image for network map display.

`setNameOnMap(name) => void`::
Sets object's name for network map display.

`setStatusCalculation(type, ...) => void`::
Sets status calculation method.

`setStatusPropagation(type, ...) => void`::
Sets status propagation method.

`unbind(object) => void`::
Unbind provided object from the current object.

`unbindFrom(object) => void`::
Unbind current object from the provided object.

`unmanage() => void`::
Set object into unmanaged state.

`writeMaintenanceJournal(description) => void`::
Add entry to maintenance journal.
====
