[.nxsl-class]
[[class-accesspoint]]
=== AccessPoint

Represents NetXMS access point object.

==== Instance attributes

[.attr-list]
--
[[accesspoint-apState]]
apState => String::
State from <<accesspoint-state>>

[[accesspoint-controller]]
controller => <<class-node>>::
Acess point controller of class <<class-node>>.

[[accesspoint-controllerId]]
controllerId => Integer::
Acess point controller object id.

[[accesspoint-downSince]]
downSince => Integer::
UNIX epoch timestamp down since.

[[accesspoint-index]]
index => Integer::
Index

[[accesspoint-macAddress]]
macAddress => String::
Mac address

[[accesspoint-model]]
model => String::
Model

[[accesspoint-peerInterface]]
peerInterface => <<class-interface>>::
Peer interface of class <<class-interface>>

[[accesspoint-peerNode]]
peerNode => <<class-node>>::
Peer interface of class <<class-node>>

[[accesspoint-radioInterfaces]]
radioInterfaces => <<class-radiointerface>>::
Radio interface of class <<class-radiointerface>>

[[accesspoint-serialNumber]]
serialNumber => String::
Serial number

[[accesspoint-vendor]]
vendor => String::
Vendor

[[accesspoint-wirelessDomain]]
wirelessDomain => <<class-wirelessdomain>>::
Wireless domain of class <<class-wirelessdomain>>

[[accesspoint-wirelessDomainId]]
wirelessDomainId => Integer::
Wireless domain id

[[accesspoint-wirelessStations]]
wirelessStations => String::
Wireless station of class <<class-wirelessstation>>
--

==== Constants

[[accesspoint-state]]
[cols="1,4a"]
.Access point state
|===
| Description | Value

|AP_UP
|0

|AP_UNPROVISIONED
|1

|AP_DOWN
|2

|AP_UNKNOWN
|3
|===
