[.nxsl-class]
[[class-accesspoint]]
=== AccessPoint

Represents NetXMS access point object.

==== Instance attributes

`apState => String`::
State from <<accesspoint-state>>

`controller => <<class-node>>`::
Acess point controller of class <<class-node>>.

`controllerId => Integer`::
Acess point controller object id.

`downSince => Integer`::
UNIX epoch timestamp down since.

`index => Integer`::
Index

`macAddress => String`::
Mac address

`model => String`::
Model

`peerInterface => <<class-interface>>`::
Peer interface of class <<class-interface>>

`peerNode => <<class-node>>`::
Peer interface of class <<class-node>>

`radioInterfaces => <<class-radiointerface>>`::
Radio interface of class <<class-radiointerface>>

`serialNumber => String`::
Serial number

`vendor => String`::
Vendor

`wirelessDomain => <<class-wirelessdomain>>`::
Wireless domain of class <<class-wirelessdomain>>

`wirelessDomainId => Integer`::
Wireless domain id

`wirelessStations => String`::
Wireless station of class <<class-wirelessstation>>

==== Constants

[[accesspoint-state]]
[cols="1,4a"]
.Access point state
|===
| Description | Value

|AP_UP
|0

|AP_UNPROVISIONED
|1

|AP_DOWN  
|2

|AP_UNKNOWN  
|3
|===
