[[class-alarm]]
=== Alarm

Represents NetXMS alarm.

==== Instance attributes

`ackBy => Number`::
ID of user who acknowledged this alarm.

`creationTime => Number`::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the alarm creation time.

`dciId => Number`::
If alarm was created as a result of DCI threshold violation, this attribute will contain ID of the DCI.

`eventCode => Number`::
Event code of originating event.

`eventId => Number`::
ID of originating event.

`eventTagList => Number`::
List of event tags as a coma separated string

`helpdeskReference => String`::
Helpdesk system reference (e.g. issue ID).

`helpdeskState => Number`::
Helpdesk state:
  * 0 = Ignored
  * 1 = Open
  * 2 = Closed

`id => Number`::
Unique identifier of the alarm.

`key => String`::
Alarm key.

`lastChangeTime => Number`::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the last update.

`message => String`::
Alarm message.

`originalSeverity => Number`::
Original severity of the alarm.

`repeatCount => Number`::
Repeat count.

`resolvedBy => Number`::
ID of user who resolved this alarm.

`ruleGuid => String`::
Guid of the rule that generated the event.

`severity => Number`::
Current alarm severity.

`sourceObject => Number`::
ID of the object where alarm is raised.

`state => Number`::
Alarm state:
  * 0 = Outstanding
  * 1 = Acknowledged
  * 2 = Resolved
  * 17 = Sticky acknowledged

==== Instance methods

`acknowledge() => Number`::
Acknowledge alarm. Return `0` on success or error code on failure.

`resolve() => Number`::
Resolve alarm. Return `0` on success or error code on failure.

`terminate() => Number`::
Terminate alarm. Return `0` on success or error code on failure.

`addComment(commentText, syncWithHelpdesk) => Number`::
Add new alarm comment.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|commentText|String|Text of the new alarm comment.
|syncWithHelpdesk|String|Optional. If synchronization with helpdesk should be done. TRUE by default.
|===

.Return

Id of the newly created alarm comment.

`getComments() => Array`::
Get array of alarm comments.

.Return

Array of <<class-alarm-comment>> objects.
