[.nxsl-class]
[[class-alarm]]
=== Alarm

Represents NetXMS alarm.

==== Instance attributes

[.attr-list]
--
[[alarm-ackBy]]
ackBy: int::
ID of user who acknowledged this alarm.

[[alarm-ackByUser]]
ackByUser => <<class-userdbobject>>::
User who acknowledged this alarm (class <<class-userdbobject>>).

[[alarm-categories]]
categories : <<class-array,Array>>::
Array with alarm category names.

[[alarm-creationTime]]
creationTime: int::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the alarm creation time.

[[alarm-dciId]]
dciId: int::
If alarm was created as a result of DCI threshold violation, this attribute will contain ID of the DCI.

[[alarm-eventCode]]
eventCode: int::
Event code of originating event.

[[alarm-eventId]]
eventId: int::
ID of originating event.

[[alarm-eventName]]
eventName: <<class-string,String>>::
Name of originating event.

[[alarm-eventTagList]]
eventTagList => Float::
List of event tags as a comma separated string

[[alarm-helpdeskReference]]
helpdeskReference: <<class-string,String>>::
Helpdesk system reference (e.g. issue ID).

[[alarm-helpdeskState]]
helpdeskState: int::
Helpdesk state:
+
  * 0 = Ignored
  * 1 = Open
  * 2 = Closed

[[alarm-id]]
id: int::
Unique identifier of the alarm.

[[alarm-impact]]
impact: <<class-string,String>>::
Alarm impact text

[[alarm-key]]
key: <<class-string,String>>::
Alarm key.

[[alarm-lastChangeTime]]
lastChangeTime: int::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the last update.

[[alarm-message]]
message: <<class-string,String>>::
Alarm message.

[[alarm-originalSeverity]]
originalSeverity: int::
Original severity of the alarm.

[[alarm-parentId]]
parentId: int::
Parent alarm id

[[alarm-repeatCount]]
repeatCount: int::
Repeat count.

[[alarm-resolvedBy]]
resolvedBy: int::
ID of user who resolved this alarm.

[[alarm-resolvedByUser]]
resolvedByUser => <<class-userdbobject>>::
User who resolved this alarm (class <<class-userdbobject>>)

[[alarm-rcaScriptName]]
rcaScriptName: <<class-string,String>>::
Name of root cause analysis script

[[alarm-relatedEvents]]
relatedEvents : <<class-array,Array>>::
Array with related event IDs.
+
[.version-added]
Added in version 6.0

[[alarm-ruleGuid]]
ruleGuid: <<class-string,String>>::
Guid of the rule that generated the event.

[[alarm-ruleDescription]]
ruleDescription: <<class-string,String>>::
Description of the rule that generated the event.

[[alarm-severity]]
severity: int::
Current alarm severity.

[[alarm-sourceObject]]
sourceObject: int::
ID of the object where alarm is raised.

[[alarm-state]]
state: int::
Alarm state:
+
  * 0 = Outstanding
  * 1 = Acknowledged
  * 2 = Resolved
  * 17 = Sticky acknowledged
--

==== Instance methods

[.method-list]
--
[[alarm-acknowledge]]
acknowledge(): int::
Acknowledge alarm. Return `0` on success or error code on failure.

[[alarm-addComment]]
addComment(commentText, syncWithHelpdesk): int::
Add new alarm comment.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|commentText|String|Text of the new alarm comment.
|syncWithHelpdesk|String|Optional. If synchronization with helpdesk should be done. TRUE by default.
|===
+
.Return
Id of the newly created alarm comment.

[[alarm-expandString]]
expandString(string): <<class-string,String>>::
Expand string by replacing macros with their values.
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|string|String to expand
|===
+
.Return
Formated string

[[alarm-getComments]]
getComments() : <<class-array,Array>>::
Get array of alarm comments.
+
.Return
Array of <<class-alarmcomment>> objects.

[[alarm-requestAiAssistantComment]]
requestAiAssistantComment(): <<class-string,String>>::
Request an AI assistant comment for this alarm.
+
.Return
String containing the AI assistant's response, or NULL if empty.

[[alarm-resolve]]
resolve(): int::
Resolve alarm. Return `0` on success or error code on failure.

[[alarm-terminate]]
terminate(): int::
Terminate alarm. Return `0` on success or error code on failure.
--

.See also
<<func-findalarmbykey>>, <<func-findalarmbykeyregex>>, <<func-findalarmbyid>>, <<class-alarmcomment>>, <<class-event>>
