[.nxsl-class]
[[class-alarm]]
=== Alarm

Represents NetXMS alarm.

==== Instance attributes

`ackBy => Integer`::
ID of user who acknowledged this alarm.

`categories => Array`::
Array with alarm category names.

`creationTime => Integer`::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the alarm creation time.

`dciId => Integer`::
If alarm was created as a result of DCI threshold violation, this attribute will contain ID of the DCI.

`eventCode => Integer`::
Event code of originating event.

`eventId => Integer`::
ID of originating event.

`eventName => String`::
Name of originating event.

`eventTagList => Float`::
List of event tags as a comma separated string

`helpdeskReference => String`::
Helpdesk system reference (e.g. issue ID).

`helpdeskState => Integer`::
Helpdesk state:
  * 0 = Ignored
  * 1 = Open
  * 2 = Closed

`id => Integer`::
Unique identifier of the alarm.

`impact => String`::
Alarm impact text

`key => String`::
Alarm key.

`lastChangeTime => Integer`::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the last update.

`message => String`::
Alarm message.

`originalSeverity => Integer`::
Original severity of the alarm.

`parentId => Integer`::
Parent alarm id

`repeatCount => Integer`::
Repeat count.

`resolvedBy => Integer`::
ID of user who resolved this alarm.

`rcaScriptName => String`::
Name of root cause analysis script

`ruleGuid => String`::
Guid of the rule that generated the event.

`ruleDescription => String`::
Description of the rule that generated the event.

`severity => Integer`::
Current alarm severity.

`sourceObject => Integer`::
ID of the object where alarm is raised.

`state => Integer`::
Alarm state:
  * 0 = Outstanding
  * 1 = Acknowledged
  * 2 = Resolved
  * 17 = Sticky acknowledged

==== Instance methods

`acknowledge() => Integer`::
Acknowledge alarm. Return `0` on success or error code on failure.

`addComment(commentText, syncWithHelpdesk) => Integer`::
Add new alarm comment.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|commentText|String|Text of the new alarm comment.
|syncWithHelpdesk|String|Optional. If synchronization with helpdesk should be done. TRUE by default.
|===

.Return

Id of the newly created alarm comment.

`expandString(string) => String`::

Expand string by replacing macros with their values.

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|string|String to expand
|===

.Return

Formated string

`getComments() => Array`::
Get array of alarm comments.

.Return

Array of <<class-alarmcomment>> objects.

`resolve() => Integer`::
Resolve alarm. Return `0` on success or error code on failure.

`terminate() => Integer`::
Terminate alarm. Return `0` on success or error code on failure.

