[.nxsl-class]
[[class-alarm]]
=== Alarm

Represents NetXMS alarm.

==== Instance attributes

[.attr-list]
--
[[alarm-ackBy]]
ackBy: int::
ID of user who acknowledged this alarm.

[[alarm-ackByUser]]
ackByUser => <<class-userdbobject>>::
User who acknowledged this alarm (class <<class-userdbobject>>).

[[alarm-categories]]
categories: <<class-array,Array>>::
Array with alarm category names.

[[alarm-creationTime]]
creationTime: int::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the alarm creation time.

[[alarm-dciId]]
dciId: int::
If alarm was created as a result of DCI threshold violation, this attribute will contain ID of the DCI.

[[alarm-eventCode]]
eventCode: int::
Event code of originating event.

[[alarm-eventId]]
eventId: int::
ID of originating event.

[[alarm-eventName]]
eventName: <<class-string,String>>::
Name of originating event.

[[alarm-eventTagList]]
eventTagList: float::
List of event tags as a comma separated string

[[alarm-helpdeskReference]]
helpdeskReference: <<class-string,String>>::
Helpdesk system reference (e.g. issue ID).

[[alarm-helpdeskState]]
helpdeskState: int::
Helpdesk state:
+
  * 0 = Ignored
  * 1 = Open
  * 2 = Closed

[[alarm-id]]
id: int::
Unique identifier of the alarm.

[[alarm-impact]]
impact: <<class-string,String>>::
Alarm impact text

[[alarm-key]]
key: <<class-string,String>>::
Alarm key.

[[alarm-lastChangeTime]]
lastChangeTime: int::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the last update.

[[alarm-message]]
message: <<class-string,String>>::
Alarm message.

[[alarm-originalSeverity]]
originalSeverity: int::
Original severity of the alarm.

[[alarm-parentId]]
parentId: int::
Parent alarm id

[[alarm-repeatCount]]
repeatCount: int::
Repeat count.

[[alarm-resolvedBy]]
resolvedBy: int::
ID of user who resolved this alarm.

[[alarm-resolvedByUser]]
resolvedByUser => <<class-userdbobject>>::
User who resolved this alarm (class <<class-userdbobject>>)

[[alarm-rcaScriptName]]
rcaScriptName: <<class-string,String>>::
Name of root cause analysis script

[[alarm-relatedEvents]]
relatedEvents: <<class-array,Array>>::
Array with related event IDs.
+
[.version-added]
Added in version 6.0

[[alarm-ruleGuid]]
ruleGuid: <<class-string,String>>::
Guid of the rule that generated the event.

[[alarm-ruleDescription]]
ruleDescription: <<class-string,String>>::
Description of the rule that generated the event.

[[alarm-severity]]
severity: int::
Current alarm severity.

[[alarm-sourceObject]]
sourceObject: int::
ID of the object where alarm is raised.

[[alarm-state]]
state: int::
Alarm state:
+
  * 0 = Outstanding
  * 1 = Acknowledged
  * 2 = Resolved
  * 17 = Sticky acknowledged
--

==== Instance methods

[.method-list]
--
[[alarm-acknowledge]]
acknowledge(): int::
Acknowledge alarm. Return `0` on success or error code on failure.

[[alarm-addComment]]
addComment(commentText, syncWithHelpdesk): int::
Add new alarm comment.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|commentText|String|Text of the new alarm comment.
|syncWithHelpdesk|String|Optional. If synchronization with helpdesk should be done. TRUE by default.
|===
+
.Return
Id of the newly created alarm comment.

[[alarm-closeHelpdeskIssue]]
closeHelpdeskIssue(): int::
+
[.version-added]
Added in version 6.1
+
Mark helpdesk issue linked to this alarm as closed. Helpdesk reference is kept, helpdesk state changes to _Closed_. Alarm must be in helpdesk state _Open_.
+
.Return
`0` on success, `5` (out of state request) if helpdesk state is not _Open_, or other error code on failure.

[[alarm-expandString]]
expandString(string): <<class-string,String>>::
Expand string by replacing macros with their values.
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|string|String to expand
|===
+
.Return
Formated string

[[alarm-getComments]]
getComments(): <<class-array,Array>>::
Get array of alarm comments.
+
.Return
Array of <<class-alarmcomment>> objects.

[[alarm-requestAiAssistantComment]]
requestAiAssistantComment(): <<class-string,String>>::
Request an AI assistant comment for this alarm.
+
.Return
String containing the AI assistant's response, or NULL if empty.

[[alarm-resolve]]
resolve(): int::
Resolve alarm. Return `0` on success or error code on failure.

[[alarm-setHelpdeskReference]]
setHelpdeskReference(reference): int::
+
[.version-added]
Added in version 6.1
+
Link this alarm to an external helpdesk issue without going through the helpdesk integration module. Sets helpdesk reference and changes helpdesk state to _Open_. Alarm must be in helpdesk state _Ignored_ (not yet linked).
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|reference|String|Helpdesk system reference (e.g. issue ID). Must not be empty.
|===
+
.Return
`0` on success, `5` (out of state request) if alarm is already linked to a helpdesk issue, `12` (invalid argument) if reference is empty, or other error code on failure.
+
[.source]
....
alarm = FindAlarmByKey("DISK_FULL_" .. $node.id);
if (alarm != null && alarm.helpdeskState == 0)
{
   rcc = alarm.setHelpdeskReference("TICKET-4711");
   if (rcc != 0)
      trace(2, "Cannot set helpdesk reference: RCC=" .. rcc);
}
....

[[alarm-terminate]]
terminate(): int::
Terminate alarm. Return `0` on success or error code on failure.

[[alarm-unlinkFromHelpdesk]]
unlinkFromHelpdesk(): int::
+
[.version-added]
Added in version 6.1
+
Remove helpdesk link from this alarm. Clears helpdesk reference and resets helpdesk state to _Ignored_. Works in any helpdesk state.
+
.Return
`0` on success or error code on failure.
--

.See also
<<func-findalarmbykey>>, <<func-findalarmbykeyregex>>, <<func-findalarmbyid>>, <<class-alarmcomment>>, <<class-event>>
