[.nxsl-class]
[[class-alarm]]
=== Alarm

Represents NetXMS alarm.

==== Instance attributes

[.attr-list]
--
[[alarm-ackBy]]
ackBy => Integer::
ID of user who acknowledged this alarm.

[[alarm-ackByUser]]
ackByUser => <<class-userdbobject>>::
User who acknowledged this alarm (class <<class-userdbobject>>).

[[alarm-categories]]
categories => Array::
Array with alarm category names.

[[alarm-creationTime]]
creationTime => Integer::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the alarm creation time.

[[alarm-dciId]]
dciId => Integer::
If alarm was created as a result of DCI threshold violation, this attribute will contain ID of the DCI.

[[alarm-eventCode]]
eventCode => Integer::
Event code of originating event.

[[alarm-eventId]]
eventId => Integer::
ID of originating event.

[[alarm-eventName]]
eventName => String::
Name of originating event.

[[alarm-eventTagList]]
eventTagList => Float::
List of event tags as a comma separated string

[[alarm-helpdeskReference]]
helpdeskReference => String::
Helpdesk system reference (e.g. issue ID).

[[alarm-helpdeskState]]
helpdeskState => Integer::
Helpdesk state:
+
  * 0 = Ignored
  * 1 = Open
  * 2 = Closed

[[alarm-id]]
id => Integer::
Unique identifier of the alarm.

[[alarm-impact]]
impact => String::
Alarm impact text

[[alarm-key]]
key => String::
Alarm key.

[[alarm-lastChangeTime]]
lastChangeTime => Integer::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the last update.

[[alarm-message]]
message => String::
Alarm message.

[[alarm-originalSeverity]]
originalSeverity => Integer::
Original severity of the alarm.

[[alarm-parentId]]
parentId => Integer::
Parent alarm id

[[alarm-repeatCount]]
repeatCount => Integer::
Repeat count.

[[alarm-resolvedBy]]
resolvedBy => Integer::
ID of user who resolved this alarm.

[[alarm-resolvedByUser]]
resolvedByUser => <<class-userdbobject>>::
User who resolved this alarm (class <<class-userdbobject>>)

[[alarm-rcaScriptName]]
rcaScriptName => String::
Name of root cause analysis script

[[alarm-relatedEvents]]
relatedEvents => Array::
Array with related event IDs.
+
[.version-added]
Added in version 6.0

[[alarm-ruleGuid]]
ruleGuid => String::
Guid of the rule that generated the event.

[[alarm-ruleDescription]]
ruleDescription => String::
Description of the rule that generated the event.

[[alarm-severity]]
severity => Integer::
Current alarm severity.

[[alarm-sourceObject]]
sourceObject => Integer::
ID of the object where alarm is raised.

[[alarm-state]]
state => Integer::
Alarm state:
+
  * 0 = Outstanding
  * 1 = Acknowledged
  * 2 = Resolved
  * 17 = Sticky acknowledged
--

==== Instance methods

[.method-list]
--
[[alarm-acknowledge]]
acknowledge() => Integer::
Acknowledge alarm. Return `0` on success or error code on failure.

[[alarm-addComment]]
addComment(commentText, syncWithHelpdesk) => Integer::
Add new alarm comment.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|commentText|String|Text of the new alarm comment.
|syncWithHelpdesk|String|Optional. If synchronization with helpdesk should be done. TRUE by default.
|===
+
.Return
Id of the newly created alarm comment.

[[alarm-expandString]]
expandString(string) => String::
Expand string by replacing macros with their values.
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|string|String to expand
|===
+
.Return
Formated string

[[alarm-getComments]]
getComments() => Array::
Get array of alarm comments.
+
.Return
Array of <<class-alarmcomment>> objects.

[[alarm-requestAiAssistantComment]]
requestAiAssistantComment() => String::
Request an AI assistant comment for this alarm.
+
.Return
String containing the AI assistant's response, or NULL if empty.

[[alarm-resolve]]
resolve() => Integer::
Resolve alarm. Return `0` on success or error code on failure.

[[alarm-terminate]]
terminate() => Integer::
Terminate alarm. Return `0` on success or error code on failure.
--

.See also
<<func-findalarmbykey>>, <<func-findalarmbykeyregex>>, <<func-findalarmbyid>>, <<class-alarmcomment>>, <<class-event>>
