[.nxsl-class]
[[class-businessservicecheck]]
=== BusinessServiceCheck

Object represents business service check

==== Instance attributes

[.attr-list]
--
[[businessservicecheck-currentTicketId]]
currentTicketId => Integer::
ID of the ticket that is currently associated with this check or 0 if check is OK

[[businessservicecheck-description]]
description => String::
Cehck description

[[businessservicecheck-failureReason]]
failureReason => String::
Reason why check have failed or null if check is not failed

[[businessservicecheck-id]]
id => Integer::
ID of the check

[[businessservicecheck-relatedDCI]]
relatedDCI => DCI::
DCI object of class <<class-dci>> that is checked or NULL if check is not DCI based

[[businessservicecheck-relatedDCIId]]
relatedDCIId => Integer::
DCI id that is checked or 0 if it is not DCI based check

[[businessservicecheck-relatedObject]]
relatedObject => NetObj::
Related object (inherited from <<class-netobj>>, exact type can be checked with <<func-classof>> function) or NULL

[[businessservicecheck-relatedObjectId]]
relatedObjectId => Integer::
ID of related objec or 0

[[businessservicecheck-state]]
state => Integer::
Current state of the business service check one of <<const-business-service-state,states>>

[[businessservicecheck-type]]
type => Integer::
Business service check one of <<const-business-service-check-type,types>>
--
