[.nxsl-class]
[[class-bytestream]]
=== ByteStream

Object represents stream of bytes


==== Instance attributes

[.attr-list]
--
[[bytestream-eos]]
eos: bool::
Indicates, if current position is in the end of byte stream

[[bytestream-pos]]
pos: int::
Current position in the byte stream

[[bytestream-size]]
size: int::
Size of byte stream in bytes
--


==== Instance methods

[.method-list]
--
[[bytestream-seek]]
seek(position): int::
Change current position in byte stream.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|position|Integer|Position to seek to
|===
+
.Return
Actual position if position change was successful or `-1` if position change was
not successful.

[[bytestream-readByte]]
readByte(): int (32 bit)::
Read byte from byte stream and return it's value.

[[bytestream-readInt16B]]
readInt16B(): int (32 bit)::
Read big-endian 16-bit signed integer from byte stream and return it's value.

[[bytestream-readInt32B]]
readInt32B(): int (32 bit)::
Read big-endian 32-bit signed integer from byte stream and return it's value.

[[bytestream-readInt64B]]
readInt64B(): int (64 bit)::
Read big-endian 64-bit signed integer from byte stream and return it's value.

[[bytestream-readUInt16B]]
readUInt16B(): int (32 bit)::
Read big-endian 16-bit unsigned integer from byte stream and return it's value.

[[bytestream-readUInt32B]]
readUInt32B(): int (32 bit)::
Read big-endian 32-bit unsigned integer from byte stream and return it's value.

[[bytestream-readUInt64B]]
readUInt64B(): int (64 bit)::
Read big-endian 64-bit unsigned integer from byte stream and return it's value.

[[bytestream-readFloatB]]
readFloatB(): floating-point number::
Read 8 bytes from stream as big-endian floating-point number and return it's
value. Deprecated from v 5.1.2, readFloat64B should be used instead.

[[bytestream-readFloat32B]]
readFloat32B(): floating-point number (32 bit)::
Read 32 bytes from stream as big-endian floating-point number and return it's
value. Added in v 5.1.2.

[[bytestream-readFloat64B]]
readFloat64B(): floating-point number (64 bit)::
Read 64 bytes from stream as big-endian floating-point number and return it's
value. Added in v 5.1.2.

[[bytestream-readInt16L]]
readInt16L(): int (32 bit)::
Read little-endian 16-bit signed integer from byte stream and return it's value.

[[bytestream-readInt32L]]
readInt32L(): int (32 bit)::
Read little-endian 32-bit signed integer from byte stream and return it's value.

[[bytestream-readInt64L]]
readInt64L(): int (64 bit)::
Read little-endian 64-bit signed integer from byte stream and return it's value.

[[bytestream-readUInt16L]]
readUInt16L(): int (32 bit)::
Read littleig-endian 16-bit unsigned integer from byte stream and return it's
value.

[[bytestream-readUInt32L]]
readUInt32L(): int (32 bit)::
Read little-endian 32-bit unsigned integer from byte stream and return it's
value.

[[bytestream-readUInt64L]]
readUInt64L(): int (64 bit)::
Read little-endian 64-bit unsigned integer from byte stream and return it's
value.

[[bytestream-readFloatL]]
readFloatL(): floating-point number::
Read 8 bytes from stream as little-endian floating-point number and return it's
value. Deprecated from v 5.1.2, readFloat64L should be used instead.

[[bytestream-readFloat32L]]
readFloat32L(): floating-point number (32 bit)::
Read 32 bytes from stream as little-endian floating-point number and return it's
value. Added in v 5.1.2.

[[bytestream-readFloat64L]]
readFloat64L(): floating-point number (64 bit)::
Read 64 bytes from stream as little-endian floating-point number and return it's
value. Added in v 5.1.2.

[[bytestream-readCString]]
readCString(): <<class-string,String>>::
Read C-string from stream and return it's value. It's expected that string in
the stream is terminates by a null character.

[[bytestream-readPString]]
readPString(): <<class-string,String>>::
Read Pascal string from stream and return it's value. It's expected that first
byte of string in the stream contains length of the string.

[[bytestream-readString]]
readString(length): <<class-string,String>>::
Read string from stream and return it's value.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|length|Integer|Length of the string
|===

[[bytestream-writeByte]]
writeByte(value): void::
Write provided value as byte to the byte stream at current position.

[[bytestream-writeInt16B]]
writeInt16B(value): void::
Write provided value to the byte stream as big-endian 16-bit integer .

[[bytestream-writeInt32B]]
writeInt32B(value): void::
Write provided value to the byte stream as big-endian 32-bit integer.

[[bytestream-writeInt64B]]
writeInt64B(value): void::
Write provided value to the byte stream as big-endian 64-bit integer.

[[bytestream-writeFloatB]]
writeFloatB(value): void::
Write provided value to the byte stream as big-endian 64-bit float. Deprecated from v 5.1.2, writeFloat64B should be used instead.

[[bytestream-writeFloat32B]]
writeFloat32B(value): void::
Write provided value to the byte stream as big-endian 32-bit float. Added in v 5.1.2.

[[bytestream-writeFloat64B]]
writeFloat64B(value): void::
Write provided value to the byte stream as big-endian 64-bit float. Added in v 5.1.2.

[[bytestream-writeInt16L]]
writeInt16L(value): void::
Write provided value to the byte stream as little-endian 16-bit integer.

[[bytestream-writeInt32L]]
writeInt32L(value): void::
Write provided value to the byte stream as little-endian 32-bit integer.

[[bytestream-writeInt64L]]
writeInt64L(value): void::
Write provided value to the byte stream as little-endian 64-bit integer.

[[bytestream-writeFloatL]]
writeFloatL(value): void::
Write provided value to the byte stream as little-endian 64-bit float. Deprecated from v 5.1.2, writeFloat64L should be used instead.

[[bytestream-writeFloat32L]]
writeFloat32L(value): void::
Write provided value to the byte stream as little-endian 32-bit float. Added in v 5.1.2.

[[bytestream-writeFloat64L]]
writeFloat64L(value): void::
Write provided value to the byte stream as little-endian 64-bit float. Added in v 5.1.2.

[[bytestream-writeCString]]
writeCString(string): void::
Write provided string to the byte stream as null-terminated string (C-string).

[[bytestream-writePString]]
writePString(string): void::
Write provided string to the byte stream as Pascal string (first byte is string length).

[[bytestream-writeString]]
writeString(string): void::
Write provided string to the byte stream.
--


==== Constructors

`ByteStream()`::
Creates new byte stream.

.Return
ByteStream object.

[.source]
....
bytestream = new ByteStream();
bytestream.writeString("xyz");
bytestream.seek(0);
while (!bytestream.eos) {
  b = bytestream.readByte();
  print(d2x(b,2) .. " "); // prints "78 79 7A"
}
....
