[.nxsl-class]
[[class-collector]]
=== Collector

Object represent collector, extends <<class-netobj>>.

==== Instance attributes

`autoBindScript => String`::
Source of the script for automatic binding.

`isAutoBindEnabled => Boolean`::
Indicate if automatic binding is enabled.

`isAutoUnbindEnabled => Boolean`::
Indicate if automatic unbinding is enabled.

==== Instance methods

[[class-collector-createCollector,Collector::createCollector()]]
`createCollector(name) => <<class-collector>>`::
Create new collector under current object

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New collector's name
|===

.Return

Newly created collector of <<class-collector>> class.

[[class-collector-createContainer,Collector::createContainer()]]
`createContainer(name) => <<class-container>>`::
Create new container under current object

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New container's name
|===

.Return

Newly created container of <<class-container>> class.

[[class-collector-createNode,Collector::createNode()]]
`createNode(name, primaryHostName, zoneUIN) => <<class-node>>`::
Create new node under current object.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Node name if second options is set or primary host name or IP address.
|primaryHostName|String|Optional. Primary host name or IP address.
|zoneUIN|Integer|Optional. New node's zone UIN.
|===

.Return

Newly created node of <<class-node>> class or NULL if failed to create

[[class-collector-createSensor,Collector::createSensor()]]
`createSensor(name, deviceClass, gateway, modbusUnitId) => <<class-sensor>>`::
Create new sensor under current object.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Sensor name
|deviceClass|Integer|Sensor device class, one of the following <<const-link-routingalgorithm,values>>. Optional, ``SensorDeviceClass::Other`` if omitted.
|gateway|<<class-netobj>>|Gateway used for communication sensor. Optional.
|modbusUnitId|Integer|MODBUS Unit ID. Optional.
|===

.Return

Newly created sensor of <<class-sensor>> class or NULL if failed to create

`setAutoBindMode(enableBind, enableUnbind) => void`::
Set automatic bind mode for the container.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|enableBind|Boolean|Script should be used for automatic binding.
|enableUnbind|Boolean|Script should be used for automatic unbinding.
|===


`setAutoBindScript(script) => void`::
Update automatic binding script source.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|script|String|Script source.
|===
