[.nxsl-class]
[[class-collector]]
=== Collector

Object represent collector, extends <<class-netobj>>.

==== Instance attributes

`autoBindScript => String`::
Source of the script for automatic binding.

`isAutoBindEnabled => Boolean`::
Indicate if automatic binding is enabled.

`isAutoUnbindEnabled => Boolean`::
Indicate if automatic unbinding is enabled.

==== Instance methods

`createCollector(name) => <<class-collector>>`::
Create new collector under current collector.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Collector name
|===

.Return

Newly created collector of <<class-collector>> class.

`createContainer(name) => <<class-container>>`::

Create new container under current collector.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Container name
|===

.Return

Newly created container of <<class-container>> class.

`createNode(name, ipAddress, zoneUIN) => <<class-node>>`::
Create new node under current collector.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Node name if second options is set or primary host name or IP address.
|ipAddress|String|Optional. Primary host name or IP address.
|zoneUIN|Integer|Optional. New node's zone.
|===

.Return

Newly created node of <<class-node>> class or NULL if failed to create

`setAutoBindMode(enableBind, enableUnbind) => void`::
Set automatic bind mode for the container.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|enableBind|Boolean|Script should be used for automatic binding.
|enableUnbind|Boolean|Script should be used for automatic unbinding.
|===


`setAutoBindScript(script) => void`::
Update automatic binding script source.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|script|String|Script source.
|===
