[.nxsl-class]
[[class-container]]
=== Container

Object represent container, extends <<class-netobj>>.

==== Instance attributes

`autoBindScript => String`::
Source of the script for automatic binding.

`isAutoBindEnabled => Boolean`::
Indicate if automatic binding is enabled.

`isAutoUnbindEnabled => Boolean`::
Indicate if automatic unbinding is enabled.

==== Instance methods

`createContainer(name) => <<class-container>>`::
Create new container under current container.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Container name
|===

.Return

Newly created container of <<class-container>> class.

`createCollector(name) => <<class-collector>>`::
Create new collector under current container.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Collector name
|===

.Return

Newly created collector of <<class-collector>> class.

[[class-container-createNode,Container::createNode()]]
`createNode(name, primaryHostName, zoneUIN) => <<class-node>>`::
Create new node under current container.

[NOTE]
This function is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Node name if second options is set or primary host name or IP address.
|primaryHostName|String|Optional. Primary host name or IP address.
|zoneUIN|Integer|Optional. New node's zone UIN.
|===

.Return

Newly created node of <<class-node>> class or NULL if failed to create

`setAutoBindMode(enableBind, enableUnbind) => void`::
Set automatic bind mode for the container.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|enableBind|Boolean|Script should be used for automatic binding.
|enableUnbind|Boolean|Script should be used for automatic unbinding.
|===


`setAutoBindScript(script) => void`::
Update automatic binding script source.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|script|String|Script source.
|===
