[.nxsl-class]
[[class-datacollectiontarget]]
=== DataCollectionTarget

Abstract class that represents any object that can collect data. Extends <<class-netobj>>.

==== Instance attributes

`templates => Array`::
Returns array of templates (<<class-template>>) applied on this object. Return value also affected by trusted nodes settings.

.Example
[.source]
....
// Log names and ids of all accessible templates for current node
templates = $node->templates;
foreach(t : templates)
{
	trace(1, "Template object: name='" . t->name . "' id=" . t->id);
}
....

==== Instance methods

`applyTemplate(template) => void`::

[NOTE]
This method is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

Apply template to node

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|template|<<class-template>>|Template object to apply
|===

`readInternalParameter(name) => String`::
Reads server internal object metric (metric with source "Internal").

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Metric name.
|===

`removeTemplate(template) => void`::

[NOTE]
This method is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

Remove template from node 

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|template|<<class-template>>|Template object to remove
|===
