[.nxsl-class]
[[class-datacollectiontarget]]
=== DataCollectionTarget

Abstract class that represents any object that can collect data. Extends <<class-netobj>>.

==== Instance attributes

[.attr-list]
--
[[datacollectiontarget-templates]]
templates: <<class-array,Array>>::
Returns array of templates (<<class-template>>) applied on this object. Return value also affected by trusted nodes settings.
+
[.source]
....
// Log names and ids of all accessible templates for current node
templates = $node.templates;
for (t : templates)
{
	trace(1, "Template object: name='" .. t.name .. "' id=" .. t.id);
}
....
--

==== Instance methods

[.method-list]
--
[[datacollectiontarget-applyTemplate]]
applyTemplate(template): void::
Apply template to node
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|template|<<class-template>>|Template object to apply
|===

[[datacollectiontarget-enableConfigurationPolling]]
enableConfigurationPolling(flag): void::
Enable or disable configuration polling for a node
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If configuration polling should be enabled.
|===

[[datacollectiontarget-enableDataCollection]]
enableDataCollection(flag): void::
Enable or disable data collection polling for a node.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If data collection polls should be enabled.
|===

[[datacollectiontarget-enableStatusPolling]]
enableStatusPolling(flag): void::
Enable or disable status polling for a node.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If status polls should be enabled.
|===

[[datacollectiontarget-readInternalParameter]]
readInternalParameter(name): <<class-string,String>>::
Reads object internal metric (metric with source "Internal").
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Metric name.
|===

[[datacollectiontarget-readInternalTable]]
readInternalTable(name): <<class-string,String>>::
Reads object internal table metric (metric with source "Internal").
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Metric name.
|===

[[datacollectiontarget-removeTemplate]]
removeTemplate(template): void::
Remove template from node
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|template|<<class-template>>|Template object to remove
|===
--
