[[class-dci]]
=== DCI

Represents Data Collection Item (DCI).

==== Instance attributes

`activeThresholdSeverity`::
// TODO: 

`comments`::
Comments (since 2.0-M5)

`dataType`::
Configured data type; possible values are:
  * DCI::INT32 (0) = Integer
  * DCI::UINT32 (1) = Unsigned integer
  * DCI::INT64 (2) = 64 bit integer
  * DCI::UINT64 (3) = 64 bit unsigned integer
  * DCI::STRING (4) = String
  * DCI::FLOAT (5) = Floating point number
  * DCI::NULL (6) = null

`description`::
Description

`errorCount`::
Number of consecutive data collection errors

`hasActiveThreshold`::
// TODO: 

`id`::
Unique DCI identifier

`instance`::
DCI instance (only for single value DCIs)

`instanceData`::
// TODO: 

`lastPollTime`::
Time of last DCI poll (either successful or not) as number of seconds since epoch (1 Jan 1970 00:00:00 UTC)

`name`::
Parameter's name

`origin`::
Data origin (source); possible values are:
  * 0 =	Internal
  * 1	= NetXMS agent
  * 2	= SNMP agent
  * 3	= Check Point SNMP agent
  * 4	= Push

`relatedObject => <<class-netobj>>`::
Related object or null if there is no object

`status`::
DCI status; possible values are:
  * 0 =	Active
  * 1	= Disabled
  * 2	= Not supported

`systemTag`::
System tag. Always empty for user-defined DCIs.

`template`::
// TODO: 

`templateId`::
// TODO: 

`templateItemId`::
// TODO: 

`type`::
DCI type:
  * 1 = single value
  * 2 = table

==== Instance methods

`forcePoll() => void`::
Start DCI force poll. 
