[.nxsl-class]
[[class-dci]]
=== DCI

Represents Data Collection Item (DCI).

==== Instance attributes

[.attr-list]
--
[[dci-activeThresholdSeverity]]
activeThresholdSeverity: int::
Severity of the active threshold. If there are no active thresholds, defaults to `0` (NORMAL).

[[dci-comments]]
comments: <<class-string,String>>::
DCI Comments

[[dci-dataType]]
dataType: int::
<<const-dci-datatype,Data type>> of the DCI.

[[dci-description]]
description: <<class-string,String>>::
Description

[[dci-errorCount]]
errorCount: int::
Number of consecutive data collection errors

[[dci-flags]]
flags: int::
DCI flags

[[dci-hasActiveThreshold]]
hasActiveThreshold: bool::
`TRUE` if DCI has active threshold

[[dci-id]]
id: int::
Unique DCI identifier

[[dci-instance]]
instance: <<class-string,String>>::
DCI instance (only for single value DCIs): %{instance}

[[dci-instanceName]]
instanceName: <<class-string,String>>::
DCI instance name (only for single value DCIs): %{instance-name}

[[dci-lastPollTime]]
lastPollTime: int64::
Time of last DCI poll (either successful or not) as number of seconds since epoch (1 Jan 1970 00:00:00 UTC)

[[dci-lastCollectionTime]]
lastCollectionTime: int64::
Time of last successful DCI poll as number of seconds since epoch (1 Jan 1970 00:00:00 UTC).
+
[.version-added]
Added in version 4.0

[[dci-name]]
name: <<class-string,String>>::
Parameter's name

[[dci-origin]]
origin: int::
<<const-dci-origin,Data origin>> of the DCI.

[[dci-pollingInterval]]
pollingInterval: int::
Current polling interval

[[dci-pollingSchedules]]
pollingSchedules: <<class-array,Array>>::
Array of custom schedules in cron format

[[dci-pollingScheduleType]]
pollingScheduleType: int::
Collection schedule:
  * 0 = Server default interval
  * 1 = Custom interval
  * 2 = Advanced schedule

[[dci-relatedObject]]
relatedObject => <<class-netobj>>::
Related object or null if there is no object

[[dci-status]]
status: int::
<<const-dci-states,Data status>> of the DCI.

[[dci-systemTag]]
systemTag: <<class-string,String>>::
System tag. Contains information about DCI Interpretation.

[[dci-template]]
template => <<class-template>>::
<<class-template,Template object>> if DCI came from Template or `NULL`.

[[dci-templateId]]
templateId: int::
Template id if DCI came from Template or 0.

[[dci-templateItemId]]
templateItemId: int::
DCI item id in template if DCI came from Template or 0.

[[dci-thresholdDisableEndTime]]
thresholdDisableEndTime: int::
UNIX time (number of seconds since epoch) till which threshold processing for
this DCI is disabled. -1 if threshold processing is disabled infinitely. 0 if
threshold processing is enabled.

[[dci-transformedDataType]]
transformedDataType: int::
Tranformed data link:https://netxms.org/documentation/nxsl-latest/#const-dci-datatypetype[type].

[[dci-type]]
type: int::
DCI type:
  * 1 = single value
  * 2 = table

[[dci-userTag]]
userTag: <<class-string,String>>::
User tag.
+
[.version-added]
Added in version 5.2
--

==== Instance methods

[.method-list]
--
[[dci-forcePoll]]
forcePoll(): void::
Start DCI force poll.
--

.See also
<<func-finddcibyname>>, <<func-finddcibydescription>>, <<func-findalldcis>>, <<func-getdcivalue>>, <<func-getdciobject>>, <<func-createdci>>, <<class-table>>, <<class-datapoint>>
