[.nxsl-class]
[[class-dci]]
=== DCI

Represents Data Collection Item (DCI).

==== Instance attributes

`activeThresholdSeverity => Integer`::
Severity of the active threshold. If there are no active thresholds, defaults to `0` (NORMAL).

`comments => String`::
DCI Comments (since 2.0-M5)

`dataType => Integer`::
<<const-dci-datatype,Data type>> of the DCI.

`description => String`::
Description

`errorCount => Integer`::
Number of consecutive data collection errors

`hasActiveThreshold => Boolean`::
`TRUE` if DCI has active threshold

`id => Integer`::
Unique DCI identifier

`instance => String`::
DCI instance (only for single value DCIs)

`instanceData => String`::
// TODO: 

`lastPollTime => Integer64`::
Time of last DCI poll (either successful or not) as number of seconds since epoch (1 Jan 1970 00:00:00 UTC)

`name => String`::
Parameter's name

`origin => Integer`::
<<const-dci-origin,Data origin>> of the DCI.

`pollingInterval => Integer`::
Current polling interval

`relatedObject => <<class-netobj>>`::
Related object or null if there is no object

`status => Integer`::
<<const-dci-origin,Data status>> of the DCI.

`systemTag => String`::
System tag. Always empty for user-defined DCIs.

`template => <<class-template>>`::
<<class-template,Template object>> if DCI came from Template or `NULL`.

`templateId`::
Template id if DCI came from Template or 0.

`templateItemId`::
DCI item id in template if DCI came from Template or 0.

`type`::
DCI type:
  * 1 = single value
  * 2 = table

==== Instance methods

`forcePoll() => void`::
Start DCI force poll. 
