[.nxsl-class]
[[class-dci]]
=== DCI

Represents Data Collection Item (DCI).

==== Instance attributes

[.attr-list]
--
[[dci-activeThresholdSeverity]]
activeThresholdSeverity => Integer::
Severity of the active threshold. If there are no active thresholds, defaults to `0` (NORMAL).

[[dci-comments]]
comments => String::
DCI Comments

[[dci-dataType]]
dataType => Integer::
<<const-dci-datatype,Data type>> of the DCI.

[[dci-description]]
description => String::
Description

[[dci-errorCount]]
errorCount => Integer::
Number of consecutive data collection errors

[[dci-flags]]
flags => Integer::
DCI flags

[[dci-hasActiveThreshold]]
hasActiveThreshold => Boolean::
`TRUE` if DCI has active threshold

[[dci-id]]
id => Integer::
Unique DCI identifier

[[dci-instance]]
instance => String::
DCI instance (only for single value DCIs): %{instance}

[[dci-instanceName]]
instanceName => String::
DCI instance name (only for single value DCIs): %{instance-name}

[[dci-lastPollTime]]
lastPollTime => Integer64::
Time of last DCI poll (either successful or not) as number of seconds since epoch (1 Jan 1970 00:00:00 UTC)

[[dci-lastCollectionTime]]
lastCollectionTime => Integer64::
Time of last successful DCI poll as number of seconds since epoch (1 Jan 1970 00:00:00 UTC). *Added in version 4.0*

[[dci-name]]
name => String::
Parameter's name

[[dci-origin]]
origin => Integer::
<<const-dci-origin,Data origin>> of the DCI.

[[dci-pollingInterval]]
pollingInterval => Integer::
Current polling interval

[[dci-pollingSchedules]]
pollingSchedules => Array::
Array of custom schedules in cron format

[[dci-pollingScheduleType]]
pollingScheduleType => Integer::
Collection schedule:
  * 0 = Server default interval
  * 1 = Custom interval
  * 2 = Advanced schedule

[[dci-relatedObject]]
relatedObject => <<class-netobj>>::
Related object or null if there is no object

[[dci-status]]
status => Integer::
<<const-dci-states,Data status>> of the DCI.

[[dci-systemTag]]
systemTag => String::
System tag. Contains information about DCI Interpretation.

[[dci-template]]
template => <<class-template>>::
<<class-template,Template object>> if DCI came from Template or `NULL`.

[[dci-templateId]]
templateId => Integer::
Template id if DCI came from Template or 0.

[[dci-templateItemId]]
templateItemId => Integer::
DCI item id in template if DCI came from Template or 0.

[[dci-thresholdDisableEndTime]]
thresholdDisableEndTime => Integer::
UNIX time (number of seconds since epoch) till which threshold processing for
this DCI is disabled. -1 if threshold processing is disabled infinitely. 0 if
threshold processing is enabled.

[[dci-transformedDataType]]
transformedDataType => Integer::
Tranformed data link:https://netxms.org/documentation/nxsl-latest/#const-dci-datatypetype[type].

[[dci-type]]
type => Integer::
DCI type:
  * 1 = single value
  * 2 = table

[[dci-userTag]]
userTag => String::
User tag. *This attribute was added in version 5.2*
--

==== Instance methods

[.method-list]
--
[[dci-forcePoll]]
forcePoll() => void::
Start DCI force poll.
--

.See also
<<func-finddcibyname>>, <<func-finddcibydescription>>, <<func-findalldcis>>, <<func-getdcivalue>>, <<func-getdciobject>>, <<func-createdci>>, <<class-table>>, <<class-datapoint>>
