[.nxsl-class]
[[class-discoverednode]]
=== DiscoveredNode

Represents NetXMS node found while *performing* network discovery. Is available as a $node in script that is set as DiscoveryFilter.

==== Instance attributes

[.attr-list]
--
[[discoverednode-agentVersion]]
agentVersion => String::
NetXMS agent version as `string`.

[[discoverednode-dnsName]]
dnsName => String::
Node's DNS name

[[discoverednode-interfaces]]
interfaces => Array::
Array with node's <<class-discoveredinterface, interfaces>>

[[discoverednode-ipAddr]]
ipAddr => String::
Node's ip address. Deprecated and will be removed in a future version, use `ipAddress` instead.

[[discoverednode-ipAddress]]
ipAddress => InetAddress::
Primary <<class-inetaddress,IP address>>. *This attribute was added in version 5.1*

[[discoverednode-isAgent]]
isAgent => Boolean::
`TRUE` if NetXMS agent detected on node

[[discoverednode-isBridge]]
isBridge => Boolean::
`TRUE` if node is a bridge

[[discoverednode-isCDP]]
isCDP => Boolean::
`TRUE` if node supports CDP (Cisco Discovery Protocol)

[[discoverednode-isLLDP]]
isLLDP => Boolean::
`TRUE` if node supports LLDP (Link Layer Discovery Protocol)

[[discoverednode-isPrinter]]
isPrinter => Boolean::
`TRUE` if node is a printer

[[discoverednode-isRouter]]
isRouter => Boolean::
`TRUE` if node is a router (has IP forwarding enabled)

[[discoverednode-isSNMP]]
isSNMP => Boolean::
`TRUE` if SNMP agent detected on node

[[discoverednode-isSONMP]]
isSONMP => Boolean::
`TRUE` if node supports SONMP/NDP (Synoptics/Nortel Discovery Protocol)

[[discoverednode-isSSH]]
isSSH => Boolean::
`TRUE` if SSH connection is available for this node

[[discoverednode-netMask]]
netMask => Integer::
Network mask

[[discoverednode-platformName]]
platformName => String::
Platform name reported by NetXMS agent

[[discoverednode-snmpOID]]
snmpOID => String::
SNMP object identifier (result of `1.3.6.1.2.1.1.2.0` request)

[[discoverednode-snmpVersion]]
snmpVersion => Integer::
Configured SNMP version:
+
* 0: SNMP version 1
* 1: SNMP version 2c
* 2: SNMP version 3

[[discoverednode-subnet]]
subnet => String::
Subnet

[[discoverednode-zone]]
zone => <<class-zone>>::
<<class-zone>> object (`null` if zoning is disabled)

[[discoverednode-zoneUIN]]
zoneUIN => Integer::
This node zone UIN
--
