[.nxsl-class]
[[class-discoverednode]]
=== DiscoveredNode

Represents NetXMS node found while *performing* network discovery. Is available as a $node in script that is set as DiscoveryFilter.

==== Instance attributes

`agentVersion => String`::
NetXMS agent version as `string`.

`dnsName => String`::
Node's DNS name

`interfaces => Array`::
Array with node's <<class-discoveredinterface, interfaces>>

`ipAddr => String`::
Node's ip address

`isAgent => Boolean`::
`TRUE` if NetXMS agent detected on node

`isBridge => Boolean`::
`TRUE` if node is a bridge

`isCDP => Boolean`::
`TRUE` if node supports CDP (Cisco Discovery Protocol)

`isLLDP => Boolean`::
`TRUE` if node supports LLDP (Link Layer Discovery Protocol)

`isPrinter => Boolean`::
`TRUE` if node is a printer

`isRouter => Boolean`::
`TRUE` if node is a router (has IP forwarding enabled)

`isSNMP => Boolean`::
`TRUE` if SNMP agent detected on node

`isSONMP => Boolean`::
`TRUE` if node supports SONMP/NDP (Synoptics/Nortel Discovery Protocol)

`isSSH => Boolean`::
`TRUE` if SSH connection is available for this node

`netMask => Integer`::
Network mask

`platformName => String`::
Platform name reported by NetXMS agent

`snmpOID => String`::
SNMP object identifier (result of `1.3.6.1.2.1.1.2.0` request)

`snmpVersion => Integer`::
Configured SNMP version:

* 0: SNMP version 1
* 1: SNMP version 2c
* 2: SNMP version 3

`subnet => String`::
Subnet

`zone => <<class-zone>>`::
<<class-zone>> object (`null` if zoning is disabled)

`zoneUIN => Integer`::
This node zone UIN

