[.nxsl-class]
[[class-discoverednode]]
=== DiscoveredNode

Represents NetXMS node found while *performing* network discovery. Is available as a $node in script that is set as DiscoveryFilter.

==== Instance attributes

[.attr-list]
--
[[discoverednode-agentVersion]]
agentVersion: <<class-string,String>>::
NetXMS agent version as `string`.

[[discoverednode-dnsName]]
dnsName: <<class-string,String>>::
Node's DNS name

[[discoverednode-interfaces]]
interfaces : <<class-array,Array>>::
Array with node's <<class-discoveredinterface, interfaces>>

[[discoverednode-ipAddr]]
ipAddr: <<class-string,String>>::
Node's ip address. Deprecated and will be removed in a future version, use `ipAddress` instead.

[[discoverednode-ipAddress]]
ipAddress => InetAddress::
+
[.version-added]
Added in version 5.1
+
Primary <<class-inetaddress,IP address>>.

[[discoverednode-isAgent]]
isAgent: bool::
`TRUE` if NetXMS agent detected on node

[[discoverednode-isBridge]]
isBridge: bool::
`TRUE` if node is a bridge

[[discoverednode-isCDP]]
isCDP: bool::
`TRUE` if node supports CDP (Cisco Discovery Protocol)

[[discoverednode-isLLDP]]
isLLDP: bool::
`TRUE` if node supports LLDP (Link Layer Discovery Protocol)

[[discoverednode-isPrinter]]
isPrinter: bool::
`TRUE` if node is a printer

[[discoverednode-isRouter]]
isRouter: bool::
`TRUE` if node is a router (has IP forwarding enabled)

[[discoverednode-isSNMP]]
isSNMP: bool::
`TRUE` if SNMP agent detected on node

[[discoverednode-isSONMP]]
isSONMP: bool::
`TRUE` if node supports SONMP/NDP (Synoptics/Nortel Discovery Protocol)

[[discoverednode-isSSH]]
isSSH: bool::
`TRUE` if SSH connection is available for this node

[[discoverednode-netMask]]
netMask: int::
Network mask

[[discoverednode-platformName]]
platformName: <<class-string,String>>::
Platform name reported by NetXMS agent

[[discoverednode-snmpOID]]
snmpOID: <<class-string,String>>::
SNMP object identifier (result of `1.3.6.1.2.1.1.2.0` request)

[[discoverednode-snmpVersion]]
snmpVersion: int::
Configured SNMP version:
+
* 0: SNMP version 1
* 1: SNMP version 2c
* 2: SNMP version 3

[[discoverednode-subnet]]
subnet: <<class-string,String>>::
Subnet

[[discoverednode-zone]]
zone => <<class-zone>>::
<<class-zone>> object (`null` if zoning is disabled)

[[discoverednode-zoneUIN]]
zoneUIN: int::
This node zone UIN
--
