[[class-event]]
=== Event

Represents NetXMS event object.

==== Instance attributes

`code => Number`::
Event code

`customMessage => String`::
Custom message set in event processing policy by calling `setMessage`. Get/set attribute.

`dci => DCI`::
DCI object of class <<class-dci>> that is source for this event or NULL if generated not by threshold

`dci => Number`::
DCI id that is source for this event or 0 if generated not by threshold

`id => Number`::
Unique event identifier.

`message => String`::
Event message. Get/set attribute.

`name => String`::
Event name.

`origin => Number`::
Origin of the event

* 0 - SYSTEM 
* 1 - AGENT 
* 2 - CLIENT
* 3 - SYSLOG
* 4 - SNMP
* 5 - NXSL
* 6 - REMOTE_SERVER 

`originTimestamp => Number`::
The time when the event was generated in the origin.

`parameters => Array`::
List of event parameters. Starting index is 1.

`parameterNames => Array`::
List of named event parameters (e.g. "dciId"), which can be accessed by `+object->parameterName+`.

`severity => Number`::
Event severity code. Get/set attribute.

`source => NetObj`::
Source object (inherited from <<class-netobj>>, exact type can be checked with <<func-classof>> function) for the event.

`sourceId => Number`::
ID of the source object for the event.

`tags => Array`::
Event tags as an array of strings.

`tagList => String`::
Event tags as a coma separated list.

`timestamp`::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the event.

`$1…$n`::
Shortcut for `parameters[n]` (e.g. "$event->parameters[3]" can be replaced with "$event->$3").

`$…`::
Named event parameters can be accessed directly by the name (e.g `+$event->dciId+`). List of available named parameters can be accessed with `parameterNames` attribute. Get/set attribute.

==== Instance methods

`setMessage(message) => void`::

Set event message to `message`.

.Parameters
[cols="1,3" grid="none", frame="none"]
|===
|message|Message string
|===

`setSeverity(severityCode) => void`::

Change event severity to `severityCode`.

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|severityCode
|Numeric severity code:

* 0 - NORMAL
* 1 - WARNING
* 2 - MINOR
* 3 - MAJOR
* 4 - CRITICAL
|===

`hasTag(tag) => Boolean`::

Return if event has specific tag.

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|tag|String tag
|===

`addParameter(name, value) => void`::

Set event parameter

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Parameter name. Optional parameter.
|value|String|Parameter value.
|===

`toJson() => String`::

Serialize object to JSON.

.Return

String representation of the object in JSON format.

`addTag(tag) => void`::

Set event tag, which can be later accessed via `tags` attribute.

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|tag|String tag
|===

`corelateTo(eventId) => void`::

Sets root cause id for the event

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|eventId|Root cause event id
|===

`expandString(String) => String`::

Expand string, by replacing macros. 

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|String|String to expand
|===

.Return

Formated string

`removeTag(tag) => void`::

Remove tag form event tag list

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|tag|String tag
|===

`toJson() => String`::

Serialize object to JSON.

.Return

String representation of the object in JSON format.
