[.nxsl-class]
[[class-event]]
=== Event

Represents NetXMS event object.

==== Instance attributes

[.attr-list]
--
[[event-code]]
code: int::
Event code

[[event-customMessage]]
customMessage: <<class-string,String>>::
Custom message set in event processing policy by calling `setMessage`. Deprecated and will be removed in a future version.

[[event-dci]]
dci => DCI::
DCI object of class <<class-dci>> that is source for this event or NULL if generated not by threshold

[[event-dciId]]
dciId: int::
DCI id that is source for this event or 0 if generated not by threshold

[[event-id]]
id: int::
Unique event identifier.

[[event-lastAlarmId]]
lastAlarmId: int::
ID of the last alarm associated with this event, or 0 if none.

[[event-lastAlarmKey]]
lastAlarmKey: <<class-string,String>>::
Key for last generated alarm for this event or null

[[event-lastAlarmMessage]]
lastAlarmMessage: <<class-string,String>>::
Message of the last alarm associated with this event, or null if none.

[[event-message]]
message: <<class-string,String>>::
Event message. Get/set attribute.

[[event-name]]
name: <<class-string,String>>::
Event name.

[[event-origin]]
origin: int::
Origin of the event
+
* 0 - SYSTEM
* 1 - AGENT
* 2 - CLIENT
* 3 - SYSLOG
* 4 - SNMP
* 5 - NXSL
* 6 - REMOTE_SERVER

[[event-originTimestamp]]
originTimestamp: int::
The time when the event was generated in the origin.

[[event-parameters]]
parameters: <<class-array,Array>>::
List of event parameters. Starting index is 1.

[[event-parameterNames]]
parameterNames: <<class-array,Array>>::
List of named event parameters (e.g. "dciId"), which can be accessed by `+object.parameterName+`.

[[event-rootId]]
rootId: int64::
Id of event that is root cause of this event or 0 if there is no such event.

[[event-severity]]
severity: int::
Event severity code. Get/set attribute.

[[event-source]]
source => NetObj::
Source object (inherited from <<class-netobj>>, exact type can be checked with <<func-classof>> function) for the event.

[[event-sourceId]]
sourceId: int::
ID of the source object for the event.

[[event-tags]]
tags: <<class-array,Array>>::
Event tags as an array of strings.

[[event-tagList]]
tagList: <<class-string,String>>::
Event tags as a comma separated list.

[[event-timestamp]]
timestamp: int::
link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the event.

[[event-paramN]]
$1…$n::
Shortcut for `parameters[n]` (e.g. "$event.parameters[3]" can be replaced with "$event.$3").

[[event-namedParam]]
$…::
Named event parameters can be accessed directly by the name (e.g `+$event.dciId+`). List of available named parameters can be accessed with `parameterNames` attribute. Get/set attribute.
--

==== Instance methods

[.method-list]
--
[[event-addParameter]]
addParameter(name, value) => void::
Set event parameter
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Parameter name. Optional parameter.
|value|String|Parameter value.
|===

[[event-addTag]]
addTag(tag) => void::
Set event tag, which can be later accessed via `tags` attribute.
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|tag|String tag
|===

[[event-correlateTo]]
correlateTo(eventId) => void::
Sets root cause id for the event
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|eventId|Root cause event id
|===

[[event-expandString]]
expandString(string): <<class-string,String>>::
Expand string by replacing macros with their values.
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|string|String to expand
|===
+
.Return
Formated string
+
[.source]
....
>>> $event.expandString("%N")
SYS_THRESHOLD_REACHED
....

[[event-getParameter]]
getParameter(name) => void::
Get parameter value by name or by index
+
.Parameters
[cols="1,3" grid="none", frame="none"]
|===
|name|Parameter name or index
|===
+
.Return
Parameter value or null

[[event-hasTag]]
hasTag(tag): bool::
Return if event has specific tag.
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|tag|String tag
|===

[[event-removeTag]]
removeTag(tag) => void::
Remove tag from event tag list
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|tag|String tag
|===

[[event-setMessage]]
setMessage(message) => void::
Set event message to `message`.
+
.Parameters
[cols="1,3" grid="none", frame="none"]
|===
|message|Message string
|===

[[event-setNamedParameter]]
setNamedParameter(name, value) => void::
Set named parameter or change value of existing named parameter
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|name|String name of parameter
|value|String value of parameter
|===

[[event-setParameter]]
setParameter(index, value) => void::
Set value of parameter or change value of existing parameter. If index corresponds
to existing parameter, the value will be set. If index is higher then existing
number of parameters, new parameter(s) will be added (if needed, parameters with
empty values will be added to reach the number of parameters indicated by index).
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|index|Integer index of parameter
|value|String value of parameter
|===

[[event-setSeverity]]
setSeverity(severityCode) => void::
Change event severity to `severityCode`.
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|severityCode
|Numeric <<const-object-status, severity code>>
|===

[[event-toJson]]
toJson(): <<class-string,String>>::
Serialize object to JSON.
+
.Return
String representation of the object in JSON format.
--

.See also
<<func-postevent>>, <<func-posteventex>>, <<func-loadevent>>, <<class-alarm>>
