[.nxsl-class]
[[class-file]]
=== FILE

Class that represents file on file system. Available only if 'NXSL.EnableFileIOFunctions' configuration parameter is turned on.
File read and write position in file depends on mode file was opened in.

==== Instance attributes

`eof => Boolean`::
If it's already end of file.

`name => String`::
File name

==== Instance methods

`close() => void`::
Close file

`read(numberOfSymbols) => String`::
Read provided number of bytes from file.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|numberOfSymbols|Integer|Number of symbol to read from file
|===

.Return
String with symbols read from file or null if file closed or end of file reached.

`readLine() => String`::
Read line from file.

.Return
String with read line from file or null if file closed or end of file reached.

`write(text) => void`::
Will write provided text to the file.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|text|String|Text to write in to the file
|===

`writeLine(text) => void`::
Will write provided text to the file and will add new line at the end.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|text|String|Text to write in to the file
|===
