[.nxsl-class]
[[class-file]]
=== FILE

Class that represents file on file system. Available only if
'NXSL.EnableFileIOFunctions' configuration parameter is turned on. Use
<<func-io-openfile, IO::OpenFile()>> function to create a new FILE object.

File read and write position in the file depends on mode file was opened in.

==== Instance attributes

[.attr-list]
--
[[file-eof]]
eof: bool::
If it's already end of file.

[[file-name]]
name: <<class-string,String>>::
File name
--

==== Instance methods

[.method-list]
--
[[file-close]]
close() => void::
Close file

[[file-read]]
read(numberOfSymbols): <<class-string,String>>::
Read provided number of bytes from file.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|numberOfSymbols|Integer|Number of symbol to read from file
|===
+
.Return
String with symbols read from file or null if file closed or end of file reached.

[[file-readline]]
readLine(): <<class-string,String>>::
Read line from file.
+
.Return
String with read line from file or null if file closed or end of file reached.

[[file-write]]
write(text) => void::
Will write provided text to the file.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|text|String|Text to write in to the file
|===

[[file-writeline]]
writeLine(text) => void::
Will write provided text to the file and will add new line at the end.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|text|String|Text to write in to the file
|===
--
