[.nxsl-class]
[[class-hardwarecomponent]]
=== HardwareComponent

Object that contains all information about node hardware component.

==== Instance Attributes

`capacity => Integer`::
Component capacity depending on the type.

`category => Integer`::
Code of the component category.

Possible values are:

[cols="1,1" grid="none", frame="none"]
|===
|Constant                                   |Value

|HardwareComponentCategory::OTHER           |0
|HardwareComponentCategory::BASEBOARD       |1
|HardwareComponentCategory::PROCESSOR       |2
|HardwareComponentCategory::MEMORY          |3
|HardwareComponentCategory::STORAGE         |4
|HardwareComponentCategory::BATTERY         |5
|HardwareComponentCategory::NETWORK_ADAPTER |6
|===

`categoryName => String`::
Component category name

`changeCode => Integer`::
Code of the changes that happened to the component during the last 
configuration poll.

Possible values are listed here: <<const-changecode>>

`description => String`::
Component description.

`index => Integer`::
Index of the component.

`location => String`::
Component installation location in the system.

`model => String`::
Component model.

`partNumber => String`::
Component part number.

`serialNumber => String`::
Component serial number.

`type => String`::
Component type depending on the category.

`vendor => String`::
Component vendor.
