[.nxsl-class]
[[class-hardwarecomponent]]
=== HardwareComponent

Object that contains all information about node hardware component.

==== Instance Attributes

[.attr-list]
--
[[hardwarecomponent-capacity]]
capacity: int::
Component capacity depending on the type.

[[hardwarecomponent-category]]
category: int::
Code of the component category.
+
Possible values are:
+
[cols="1,1" grid="none", frame="none"]
|===
|Constant                                   |Value

|HardwareComponentCategory::OTHER           |0
|HardwareComponentCategory::BASEBOARD       |1
|HardwareComponentCategory::PROCESSOR       |2
|HardwareComponentCategory::MEMORY          |3
|HardwareComponentCategory::STORAGE         |4
|HardwareComponentCategory::BATTERY         |5
|HardwareComponentCategory::NETWORK_ADAPTER |6
|===

[[hardwarecomponent-categoryname]]
categoryName: <<class-string,String>>::
Component category name

[[hardwarecomponent-changecode]]
changeCode: int::
Code of the changes that happened to the component during the last
configuration poll.
+
Possible values are listed here: <<const-changecode>>

[[hardwarecomponent-description]]
description: <<class-string,String>>::
Component description.

[[hardwarecomponent-index]]
index: int::
Index of the component.

[[hardwarecomponent-location]]
location: <<class-string,String>>::
Component installation location in the system.

[[hardwarecomponent-model]]
model: <<class-string,String>>::
Component model.

[[hardwarecomponent-partnumber]]
partNumber: <<class-string,String>>::
Component part number.

[[hardwarecomponent-serialnumber]]
serialNumber: <<class-string,String>>::
Component serial number.

[[hardwarecomponent-type]]
type: <<class-string,String>>::
Component type depending on the category.

[[hardwarecomponent-vendor]]
vendor: <<class-string,String>>::
Component vendor.
--
