[.nxsl-class]
[[class-inetaddress]]
=== InetAddress

Object that contains all information about network address

==== Instance attributes

`address => String`::
IP address

`family => String`::
Internet address, one of:

 * inet
 * inet6
 * unspec

`isAnyLocal => Boolean`::
`TRUE` if address is a wildcard address

`isBroadcast => Boolean`::
`TRUE` if address is a broadcast address

`isLinkLocal => Boolean`::
`TRUE` if address is a link local address

`isLoopback => Boolean`::
`TRUE` if address is a loopback address

`isMulticast => Boolean`::
`TRUE` if address is a multicast address

`isValid => Boolean`::
`TRUE` if address valid

`isValidUnicast => Boolean`::
`TRUE` if address valid unicast

`mask => Integer`::
Address bit mask

==== Constructors

`InetAddress()`::
Constructor for internet address

.Return

InetAddress object 

`InetAddress(address)`::
Constructor for internet address

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|address|String|IP address as a string
|===

.Return

InetAddress object 
