[.nxsl-class]
[[class-inetaddress]]
=== InetAddress

Object that contains all information about network address

==== Instance attributes

[.attr-list]
--
[[inetaddress-address]]
address => String::
IP address

[[inetaddress-family]]
family => String::
Internet address, one of:
+
 * inet
 * inet6
 * unspec

[[inetaddress-isanylocal]]
isAnyLocal => Boolean::
`TRUE` if address is a wildcard address

[[inetaddress-isbroadcast]]
isBroadcast => Boolean::
`TRUE` if address is a broadcast address

[[inetaddress-islinklocal]]
isLinkLocal => Boolean::
`TRUE` if address is a link local address

[[inetaddress-isloopback]]
isLoopback => Boolean::
`TRUE` if address is a loopback address

[[inetaddress-ismulticast]]
isMulticast => Boolean::
`TRUE` if address is a multicast address

[[inetaddress-issubnetbase]]
isSubnetBase => Boolean::
`TRUE` if address is a subnet base address

[[inetaddress-issubnetbroadcast]]
isSubnetBroadcast => Boolean::
`TRUE` if address is a subnet broadcast address

[[inetaddress-isvalid]]
isValid => Boolean::
`TRUE` if address valid

[[inetaddress-isvalidunicast]]
isValidUnicast => Boolean::
`TRUE` if address valid unicast

[[inetaddress-mask]]
mask => Integer::
Address bit mask

[[inetaddress-subnet]]
subnet => InetAddress::
Subnet base address
--

==== Instance methods

[.method-list]
--
[[inetaddress-contains]]
contains(address) => void::
If subnet contains internet address
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|address|<<class-inetaddress>>|Address to check for
|===
+
.Return
`TRUE` if contains, otherwise `FALSE`
+
[.source]
....
r = InetAddress("192.168.56.0", 24).contains($node.ipAddress);
println(r); // will print "true", if primary IP address of node is in that subnet
....

[[inetaddress-equals]]
equals(address) => void::
If addresses are equal
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|address|<<class-inetaddress>>|Address to check to
|===
+
.Return
`TRUE` if addresses are equal, otherwise `FALSE`

[[inetaddress-inrange]]
inRange(addressStart, addressEnd) => void::
If address is in range
+
[.source]
....
r = $node.ipAddress.inRange(InetAddress("192.168.56.10"), InetAddress("192.168.56.20"));
println(r); // will print "true", if primary IP address of node is in range
....
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|addressStart|<<class-inetaddress>>|Start of the range address
|addressEnd|<<class-inetaddress>>|End of the range address
|===
+
.Return
`TRUE` if adresse is in range, otherwise `FALSE`

[[inetaddress-samesubnet]]
sameSubnet(address) => void::
If adresses are in the same subnet (using mask bits from this InetAddress)
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|address|<<class-inetaddress>>|IP address
|===
+
.Return
`TRUE` if adresses are in the same subnet, otherwise `FALSE`
--

==== Constructors

`InetAddress()`::
Constructor for internet address
+
.Return
+
InetAddress object

`InetAddress(address, mask)`::
Constructor for internet address
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|address|String|IP address as a string
|mask|integer|mask in CIDR notation (optional parameter)
|===
+
.Return
+
InetAddress object
