[[class-interface]]
=== Interface

Represent interface object. Inherit all attributes and methods of the <<class-netobj>> class.

// TODO: formatting, types

==== Constants

[[enum-interface-state]]
.Interface states
|===
| Code | Description

| 0    | Unknown
| 1    | Up
| 2    | Down
| 3    | Testing
|===

[[enum-interface-expected-state]]
.Interface expected states
|===
| Code | Description

| 0    | Up
| 1    | Down
| 2    | Ignore
|===

==== Instance attributes

`adminState`::
Administrative <<enum-interface-state,state>> of the interface.

`alias`::
Interface alias (usually value of SNMP ifAlias).

`bridgePortNumber`::
Bridge port number for this interface.

`chassis`::
Parent chassis

`description`::
Interface description

`dot1xBackendAuthState`::
802.1x back-end authentication state

`dot1xPaeAuthState`::
802.1x PAE authentication state

`expectedState`::
<<enum-interface-expected-state,Expected state>> of the interface.

`flags`
Interface flags (bit mask, `uint32`).

`icmpAverageRTT => Integer`::
ICMP average response time for current interface. Will return null if no information.

`icmpLastRTT => Integer`::
ICMP last response time for current interface. Will return null if no information.

`icmpMaxRTT => Integer`::
ICMP maximal response time for current interface. Will return null if no information.

`icmpMinRTT => Integer`::
ICMP minimal response time for current interface. Will return null if no information.

`icmpPacketLoss => Integer`::
ICMP packet loss for current interface. Will return null if no information.

`ifIndex`::
Interface index.

`ifType`::
Interface type

`ipAddressList -> ?`::
// TODO: 

`ipNetMask`::
IP network mask (number of bits).

`isExcludedFromTopology`::
`TRUE` if this interface excluded from network topology

`isIncludedInIcmpPoll`::
`TRUE` if this interface is included in ICMP statistics

`isLoopback`::
`TRUE` if this interface is a loopback

`isManuallyCreated`::
`TRUE` if this interface object was created manually by NetXMS administrator

`isPhysicalPort`::
`TRUE` if this interface object represents physical port

`macAddr`::
String representation of MAC address separated by ":".

`module`::
Module

`mtu`::
Interface MTU (0 if unknown).

`node`::
Parent node object

`operState`::
Operational <<enum-interface-state,state>>.

`peerInterface`::
Peer interface object if known, otherwise `null`.

`peerNode`::
Peer <<class-node,node object>> if known, otherwise `null`.

`pic => Integer`::
Phisical location.

`port= > Integer`::
Port number.

`speed`::
Speed of the interface.

`vlans -> ?`::
// TODO: 

`zone`::
<<class-zone>> object (null if zoning is disabled).

`zoneUIN -> Integer`::
Zone UIN of this interface.

==== Instance methods

`setExcludeFromTopology(excluded) => void`::

Change `isExcludedFromTopology` flag.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|excluded|Boolean|`TRUE` if interface should be excluded.
|===

`setExpectedState(newState) => void`::

Set expected state to `newState`.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|newState|Number|New state as defined by <<enum-interface-expected-state>>.
|===

`setIncludeInIcmpPoll(enabled) => void`::

Enabele/Disable ICMP statistics collection for current interface.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|enabled|Boolean|If this interface should be included in ICMP statistics.
|===

