[.nxsl-class]
[[class-jsonobject]]
=== JsonObject

Represents JSON object.

[NOTE]
To parse string into JsonObject use <<func-jsonparse>>.

==== Instance attributes

Attribute values can be accessed in the same way as instance attribute.

==== Instance methods

[.method-list]
--
[[jsonobject-get]]
get(key) => ?::
Returns attribute value by the key. Value type depends on the type used in JSON.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|key|String|Attribute key
|===
+
.Return
Attribute value

[[jsonobject-keys]]
keys(): <<class-array,Array>>::
Returns attribute array
+
.Return
Attribute array

[[jsonobject-serialize]]
serialize(): <<class-string,String>>::
Returns string with serialized JSON
+
.Return
String with JSON

[[jsonobject-set]]
set(key, value) => void::
Sets attribute referenced by key to the given value.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|key|String|Attribute key
|value|String|Attribute new value
|===
--

==== Constructors

`JsonObject()`::
Creates new JSON object.
+
.Return
+
JsonObject object

`JsonObject(object)`::
Creates new JSON object with attributes and values from NXSL object or hashmap.
+
[.version-added]
Added in version 5.3
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|object|NXSL object
|===
+
.Return
+
JsonObject object
