[.nxsl-class]
[[class-netobj]]
=== NetObj

Base class for all NetXMS objects. Extends <<class-object>>.

==== Instance attributes

[NOTE]
Object custom attributes can be accessed in the same way as instance attribute.
If name of the custom attribute overlaps with the instance attribute, method <<class-netobj-getcustomattribute>> should be used instead.

[.attr-list]
--
[[netobj-alarms]]
alarms => array::
List of active <<class-alarm, Alarms>> for this object.

[[netobj-alarmStats]]
alarmStats => array::
Integer array that consists of 5 numbers - each number represents number of alarms for this and child objects for each of severity.

[[netobj-alias]]
alias => String::
Object alias. For interfaces it is automatically collected on configuration poll (e.g. from SNMP ifAlias).

[[netobj-asset]]
asset => <<class-asset>>::
Reference to <<class-asset,asset class>> of asset linked to this object.

[[netobj-assetId]]
assetId => Integer::
Id of linked asset object.

[[netobj-assetProperties]]
assetProperties => <<class-assetproperties>>::
Reference to <<class-assetproperties,asset properties class>> of asset linked to this object.

[[netobj-backupZoneProxy]]
backupZoneProxy => Node::
Currently selected backup <<class-node,zone proxy>> (`null` if zoning is disabled or backup proxy is not assigned)

[[netobj-backupZoneProxyId]]
backupZoneProxyId => Integer::
ID of currently selected backup zone proxy (`0` if zoning is disabled or backup proxy is not assigned)

[[netobj-category]]
category => String::
Object's category name

[[netobj-categoryId]]
categoryId => Integer::
Object's category ID

[[netobj-children]]
children => array::
List of child objects (inherited from <<class-netobj>>). Use <<func-classof>> to differentiate.

[[netobj-city]]
city => String::
Postal address - city.

[[netobj-comments]]
comments => String::
Object comments.

[[netobj-country]]
country => String::
Postal address - country.

[[netobj-creationTime]]
creationTime => Integer64::
Object creation time as UINX timestamp

[[netobj-customAttributes]]
customAttributes => HashMap::
Hash map of object custom attributes.

[[netobj-district]]
district => String::
Postal address - district.

[[netobj-geolocation]]
geolocation => GeoLocation::
Object <<class-geolocation,geographical location>>.

[[netobj-guid]]
guid => String::
Object GUID as `string`.

[[netobj-id]]
id => Integer::
Unique object identifier.

[[netobj-ipAddr]]
ipAddr => String::
Primary IP address. Deprecated and will be removed in a future version, use `ipAddress` instead.

[[netobj-ipAddress]]
ipAddress => InetAddress::
+
[.version-added]
Added in version 5.1
+
Primary <<class-inetaddress,IP address>>.

[[netobj-isInMaintenanceMode]]
isInMaintenanceMode => Boolean::
Maintenance mode indicator (`true` if object currently is in maintenace mode).

[[netobj-maintenanceInitiator]]
maintenanceInitiator => Integer::
Maintenance initiator user id

[[netobj-mapImage]]
mapImage => String::
GUID of object image used for representation on the maps.

[[netobj-name]]
name => String::
Object name.

[[netobj-nameOnMap]]
nameOnMap => String::
Object name displayed on map.

[[netobj-parents]]
parents => array::
List of direct parents for this object (inherited from <<class-netobj>>, most likely either <<class-container>> or <<class-cluster>>).

[[netobj-postcode]]
postcode => String::
Postal address - postal code.

[[netobj-primaryZoneProxy]]
primaryZoneProxy => Node::
currently selected primary <<class-node,zone proxy>> (`null` if zoning is disabled or primary proxy is not assigned)

[[netobj-primaryZoneProxyId]]
primaryZoneProxyId => Integer::
ID of currently selected primary zone proxy (`0` if zoning is disabled or primary proxy is not assigned)

[[netobj-region]]
region => String::
Postal address - region.

[[netobj-responsibleUsers]]
responsibleUsers => Array::
Array with user objects that are added as responsible users for this object. Objects are <<class-user>> or <<class-usergroup>>

[[netobj-state]]
state => Integer::
Current object state. One of: <<const-node-state>>, <<const-cluster-state>>, <<const-sensor-state>>

[[netobj-status]]
status => Integer::
Current <<const-object-status,object status>>.

[[netobj-streetAddress]]
streetAddress => String::
Postal address - street.

[[netobj-type]]
type => Integer::
<<enum-object-type,Object type>>.
--

==== Instance methods

[.method-list]
--
[[class-netobj-bind,NetObj::bind()]]
bind(childObject) => void::
Bind `childObject` to the current object as a child.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to bind as a child to the current object.
|===

[[class-netobj-bindto,NetObj::bindTo()]]
bindTo(parentObject) => void::
Bind current object to `parentObject` as a child.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to bind as a parent to the current object.
|===

[[netobj-calculateDowntime]]
calculateDowntime(tag, periodStart, periodEnd) => Array::
Calculate node downtime
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|tag|String|downtime tag
|periodStart|Integer|link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the period start
|periodEnd|Integer|link:https://en.wikipedia.org/wiki/Unix_time[Unix timestamp] of the period end
|===
+
.Return
Array of <<class-downtimeinfo>> objects.

[[netobj-clearGeoLocation]]
clearGeoLocation() => void::
Clears GeoLocation data from the node

[[netobj-createUserAgentNotification]]
createUserAgentNotification(message, startTime, endTime, showOnStartup) => Integer::
Send user agent notification
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|message|String|message to be sent
|startTime|String|start time of message delivery
|endTime|String|end time of message delivery
|showOnStartup|String|`TRUE` to show message on startup (optional, defaults to false)
|===
+
.Return
Message id

[[class-netobj-delete,NetObj::delete()]]
delete() => void::
Deletes current object.

[[class-netobj-deletecustomattribute,NetObj::deleteCustomAttribute()]]
deleteCustomAttribute(name) => void::
Delete custom attribute.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Name of the attribute to delete.
|===

[[class-netobj-entermaintenance,NetObj::enterMaintenance()]]
enterMaintenance() => void::
Enable maintenance mode for the object.

[[netobj-expandString]]
expandString(string) => String::
Expand string by replacing macros with their values.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|string|String|String to expand
|===
+
.Return
Formated string
+
[.source]
....
>>> $node.expandString("%n")
My node name
....

[[class-netobj-getcustomattribute,NetObj::getCustomAttribute()]]
getCustomAttribute(name) => String::
Returns value of the custom attribute with the provided name.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Name of the attribute to get value from.
|===
+
Alternatively, attributes can be accessed as instance attribues (with `.`,
attribute should exist) or by using `attribute@object` notion (which will return
`null` instead of runtime error if attribue is missing).

[[netobj-getResponsibleUsers]]
getResponsibleUsers(tag) => array::
Returns list of responsible users with specific tag. Full list is acceessible via .responsibleUsers
+
List of allowed tags are controlled by server parameter "Objects.ResponsibleUsers.AllowedTags".
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|level|String|Tag
|===
+
.Return
Array with user objects that are added as responsible users for this object.
Objects are <<class-user>> or <<class-usergroup>>
+
This function return empty list if no users or groups are found for the tag.

[[netobj-isChild]]
isChild(object) => Boolean::
If provided object is child of this object
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to check
|===
+
.Return
TRUE if provided object is child of this object

[[netobj-isDirectChild]]
isDirectChild(object) => Boolean::
If provided object is direct child of this object
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to check
|===
+
.Return
TRUE if provided object is direct child of this object

[[netobj-isDirectParent]]
isDirectParent(object) => Boolean::
If provided object is direct parent of this object
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to check
|===
+
.Return
TRUE if provided object is direct parent of this object

[[netobj-isParent]]
isParent(object) => Boolean::
If provided object is parent of this object
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to check
|===
+
.Return
TRUE if provided object is parent of this object

[[class-netobj-leavemaintenance,NetObj::leaveMaintenance()]]
leaveMaintenance() => void::
Disable maintenance mode for the object.

[[netobj-manage]]
manage() => void::
Sets object to managed state. Has no affect if object already managed.

[[netobj-readMaintenanceJournal]]
readMaintenanceJournal(startTime, endTime) => Array::
Read maintenance entries
+
.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|startTime|Integer|Period start
|endTime|Integer|Period end
|===
+
.Return
Array with <<class-maintenancejournalrecord>> objects

[[netobj-rename]]
rename(name) => void::
Rename object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New object name
|===

[[netobj-setAlias]]
setAlias(name) => void::
Set object alias name
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New alias name
|===

[[netobj-setCategory]]
setCategory(idOrName) => void::
Set object category id or name (used to get object display image)
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|idOrName|String|ID or name of category
|===

[[netobj-setComments]]
setComments(comment, [isMarkdown]) => void::
Set object comments
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|comment  |String|Comment to be set
|isMarkdown|Boolean|Optional second argument ( v 5.1.2 ). If it is logical "true", Markdown indicator will be added if not present already; if it is logical "false" (but not NULL), Markdown indicator will be removed if present; if it is NULL or omitted, comment will be set as is (retaining existing behavior).
|===

[[netobj-setCustomAttribute]]
setCustomAttribute(key, value, inherit=false) => void::
Update or create custom attribute with the given key and value.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|key|String|Attribute key
|value|String|Attribute value
|inherit|Boolean|Optional parameter. If not set - inheritance will not be changed. `true` to inherit, `false` not to inherit.
|===

[[netobj-setGeoLocation]]
setGeoLocation(newLocation) => void::
Sets node geographical <<class-geolocation,location>>.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|newLocation|<<class-geolocation>>|
|===

[[netobj-setMapImage]]
setMapImage(image) => void::
Sets object image, that will be used to display object on network map
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|image|String|GUID or name of image from image library
|===

[[netobj-setNameOnMap]]
setNameOnMap(name) => void::
Sets object's name, that will be used to display object on network map
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New object's name on map
|===

[[netobj-setStatusCalculation]]
setStatusCalculation(type, ...) => void::
Sets status calculation method.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|type|Integer|Status calculation type. One of <<enum-status-calculation-type>>
|...|Integer(s)|If single threshold or multiple thresholds type is selected, then threshold or thresholds in percentage should be provided as next parameters.
|===

[[netobj-setStatusPropagation]]
setStatusPropagation(type, ...) => void::
Sets status propagation method.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|type|Integer|Status propagation type. One of <<enum-status-propagation-type>>
|...|Integer(s)| For fixed value type - value (<<const-object-status>>) should be provided. For relative - offset should be provided. For severity - severity mapping should be provided (4 numbers <<const-object-status>>).
|===

[[class-netobj-unbind,NetObj::unbind()]]
unbind(object) => void::
Unbind provided object from the current object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to unbind from the current object.
|===

[[class-netobj-unbindfrom,NetObj::unbindFrom()]]
unbindFrom(object) => void::
Unbind current object from the provided object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to unbind from the current object.
|===

[[netobj-unmanage]]
unmanage() => void::
Set object into unmanaged state. Has no effect if object is already in unmanaged state.

[[netobj-writeMaintenanceJournal]]
writeMaintenanceJournal(description) => void::
Add entry to maintenance journal
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|description|String|Message to be added
|===
--

==== Constants

[[enum-object-type]]
[cols="1,4a"]
.Object Types
|===
| Code | Description

| 0
| Generic

| 1
| Subnet

| 2
| Node

| 3
| Interface

| 4
| Network

| 5
| Container

| 6
| Zone

| 7
| Service Root

| 8
| Template

| 9
| Template Group

| 10
| Template Root

| 11
| Network Service

| 12
| VPN Connector

| 13
| Condition

| 14
| Cluster

| 15
| Business Service Prototype

| 16
| Asset

| 17
| Asset Group

| 18
| Asset Root

| 19
| Network Map Root

| 20
| Network Map Group

| 21
| Network Map

| 22
| Dashboard Root

| 23
| Dashboard

| 27
| Business Service Root

| 28
| Business Service

| 29
| Collector

| 31
| Mobile Device

| 32
| Rack

| 33
| Access Point

| 34
| Wireless Domain

| 35
| Chassis

| 36
| Dashboard Group

| 37
| Sensor


|===

[[enum-status-calculation-type]]
[cols="1,4a"]
.Status callculation types
|===
| Code | Description

| 0
| Default

| 1
| Most critical

| 2
| Single threshold

| 3
| Multiple thresholds

|===

[[enum-status-propagation-type]]
[cols="1,4a"]
.Status propagation types
|===
| Code | Description

| 0
| Default

| 1
| Unchanged

| 2
| Fixed

| 3
| Relative

| 4
| Translated

|===

[[enum-state]]
[cols="1,4a"]
.Status propagation types
|===
| Code | Description

| 0
| Default

| 1
| Unchanged

| 2
| Fixed

| 3
| Relative

| 4
| Translated

|===
