[.nxsl-class]
[[class-netobj]]
=== NetObj

Base class for all NetXMS objects.

==== Instance attributes

NOTE: Object custom attributes can be accessed in the same way as instance attribute.
If name of the custom attribute overlaps with the instance attribute, method <<class-netobj-getcustomattribute>> should be used instead.

`alarms => array`::
List of active <<class-alarm, Alarms>> for this object.

`alias => String`::
Object alias. For interfaces it is automatically collected on configuration poll (e.g. from SNMP ifAlias).

`backupZoneProxy => Node`::
Currently selected backup <<class-node,zone proxy>> (`null` if zoning is disabled or backup proxy is not assigned)

`backupZoneProxyId => Integer`::
ID of currently selected backup zone proxy (`0` if zoning is disabled or backup proxy is not assigned)

`children => array`::
List of child objects (inherited from <<class-netobj>>). Use <<func-classof>> to differentiate.

`city => String`::
Postal address - city.

`comments => String`::
Object comments.

`country => String`::
Postal address – country.

`creationTime => Integer64`::
Object creation time as UINX timestamp

`customAttributes`::
Hash map of object custom attributes.

`geolocation => GeoLocation`::
Object <<class-geolocation,geographical location>>.

`guid => String`::
Object GUID as `string`.

`id => Integer`::
Unique object identifier.

`ipAddr => String`::
Primary IP address.

`isInMaintenanceMode => Boolean`::
Maintenance mode indicator (`true` if object currently is in maintenace mode).

`maintenanceInitiator => Integer`::
Maintenance initiator user id

`mapImage => String`::
GUID of object image used for representation on the maps.

`name => String`::
Object name.

`nameOnMap => String`::
Object name displayed on map.

`parents => array`::
List of direct parents for this object (inherited from <<class-netobj>>, most likely either <<class-container>> or <<class-cluster>>).

`postcode => String`::
Postal address – postal code.

`primaryZoneProxy => Node`::
currently selected primary <<class-node,zone proxy>> (`null` if zoning is disabled or primary proxy is not assigned)

`primaryZoneProxyId => Integer`::
ID of currently selected primary zone proxy (`0` if zoning is disabled or primary proxy is not assigned)

`responsibleUsers => Array`::
Array with user objects that are added as responsible users for this object. Objects are <<class-user>> or <<class-user-group>>

`state => Integer`::
Current object state. One of: <<const-node-state>>, <<const-cluster-state>>, <<const-sensor-state>>

`status => Integer`::
Current <<const-object-status,object status>>.

`streetAddress => String`::
Postal address – street.

`type => Integer`::
<<enum-object-type,Object type>>.

==== Instance methods

[[class-netobj-bind,NetObj::bind()]]
`bind(childObject) => void`::

[NOTE]
This method is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

Bind `childObject` to the current object as a child.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to bind as a child to the current object.
|===

[[class-netobj-bindto,NetObj::bindTo()]]
`bindTo(parentObject) => void`::

[NOTE]
This method is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

Bind current object to `parentObject` as a child.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to bind as a parent to the current object.
|===

`clearGeoLocation() => void`::
Clears GeoLocation data from the node

[[class-netobj-delete,NetObj::delete()]]
`delete() => void`::
Deletes current object.

[[class-netobj-deletecustomattribute,NetObj::deleteCustomAttribute()]]
`deleteCustomAttribute(name) => void`::
Delete custom attribute.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Name of the attribute to delete.
|===

`isDirectChild(object) => Boolean`::
If provided object is direct child of this object

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to check
|===

.Return
TRUE if provided object is direct child of this object

`isDirectParent(object) => Boolean`::
If provided object is direct parent of this object

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to check
|===

.Return
TRUE if provided object is direct parent of this object


[[class-netobj-entermaintenance,NetObj::enterMaintenance()]]
`enterMaintenance() => void`::
Enable maintenance mode for the object.

`expandString(string) => String`::

Expand string by replacing macros with their values.

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|string|String to expand
|===

.Return

Formated string

.Example
[.source]
....
>>> $node->expandString("%n")
My node name
....

[[class-netobj-getcustomattribute,NetObj::getCustomAttribute()]]
`getCustomAttribute(name) => String`::
Returns value of the custom attribute with the provided name.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Name of the attribute to get value from.
|===

`isChild(object) => Boolean`::
If provided object is child of this object

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to check
|===

.Return
TRUE if provided object is child of this object

`isParent(object) => Boolean`::
If provided object is parent of this object

.Parameters
[cols="1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to check
|===

.Return
TRUE if provided object is parent of this object


[[class-netobj-leavemaintenance,NetObj::leaveMaintenance()]]
`leaveMaintenance() => void`::
Disable maintenance mode for the object.

`manage() => void`::
Sets object to managed state. Has no affect if object already managed.

`rename(name) => void`::
Rename object.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New object name
|===

`setAlias(name) => void`::
Set object alias name

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New alias name
|===

`setCategory(idOrName) => void`::
Set object category id or name (used to get object display image)

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|idOrName|String|ID or name of category
|===

`setComments(comment) => void`::
Set object comments

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|comment|String|Comment to be set
|===

`setCustomAttribute(key, value, inherit=false) => void`::
Update or create custom attribute with the given key and value.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|key|String|Attribute key
|value|String|Attribute value
|inherit|Boolean|Optional parameter. If not set - inheritance will not be changed. `true` to inherit, `false` not to inherit.
|===

`setGeoLocation(newLocation) => void`::
Sets node geographical <<class-geolocation,location>>.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|newLocation|<<class-geolocation>>|
|===

`setMapImage(image) => void`::
Sets object image, that will be used to display object on network map

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|image|String|GUID or name of image from image library
|===

`setNameOnMap(name) => void`::
Sets object's name, that will be used to display object on network map

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New object's name on map
|===

`setStatusCalculation(type, ...) => void`::
Sets status calculation method.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|type|Integer|Status calculation type. One of <<enum-status-calculation-type>>
|...|Integer(s)|If single threshold or multiple thresholds type is selected, then threshold or thresholds in percentage should be provided as next parameters.
|===

`setStatusPropagation(type, ...) => void`::
Sets status propagation method.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|type|Integer|Status propagation type. One of <<enum-status-propagation-type>>
|...|Integer(s)| For fixed value type - value (<<const-object-status>>) should be provided. For relative - offset should be provided. For severity - severity mapping should be provided (4 numbers <<const-object-status>>).
|===

[[class-netobj-unbind,NetObj::unbind()]]
`unbind(object) => void`::

[NOTE]
This method is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

Unbind provided object from the current object.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to unbind from the current object.
|===

[[class-netobj-unbindfrom,NetObj::unbindFrom()]]
`unbindFrom(object) => void`::

[NOTE]
This method is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

Unbind current object from the provided object.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|<<class-netobj>>|Object to unbind from the current object.
|===

`unmanage() => void`::
Set object into unmanaged state. Has no effect if object is already in unmanaged state.

==== Constants

[[enum-object-type]]
[cols="1,4a"]
.Object Types
|===
| Code | Description

| 0
| Generic

| 1
| Subnet

| 2
| Node

| 3
| Interface

| 4
| Network

| 5
| Container

| 6
| Zone

| 7
| Service Root

| 8
| Template

| 9
| Template Group

| 10
| Template Root

| 11
| Network Service

| 12
| VPN Connector

| 13
| Condition

| 14
| Cluster

|===

[[enum-status-calculation-type]]
[cols="1,4a"]
.Status callculation types
|===
| Code | Description

| 0
| Default

| 1
| Most critical

| 2
| Single threshold

| 3
| Multiple thresholds

|===

[[enum-status-propagation-type]]
[cols="1,4a"]
.Status propagation types
|===
| Code | Description

| 0
| Default

| 1
| Unchanged

| 2
| Fixed

| 3
| Relative

| 4
| Translated

|===

[[enum-state]]
[cols="1,4a"]
.Status propagation types
|===
| Code | Description

| 0
| Default

| 1
| Unchanged

| 2
| Fixed

| 3
| Relative

| 4
| Translated

|===
