[[class-netobj]]
=== NetObj

Base class for all NetXMS objects.

// TODO: 

==== Constants

[[enum-object-status]]
.Object Statuses
|===
| Code | Description

| 0
| Normal

| 1
| Warning

| 2
| Minor

| 3
| Major

| 4
| Critical

| 5
| Unknown

| 6
| Unmanaged

| 7
| Disabled

| 8
| Testing

|===

[[enum-object-type]]
.Object Types
|===
| Code | Description

| 0
| Generic

| 1
| Subnet

| 2
| Node

| 3
| Interface

| 4
| Network

| 5
| Container

| 6
| Zone

| 7
| Service Root

| 8
| Template

| 9
| Template Group

| 10
| Template Root

| 11
| Network Service

| 12
| VPN Connector

| 13
| Condition

| 14
| Cluster

|===

==== Instance attributes

Object custom attributes can be accessed in the same way as instance attribute, if names do not overlap. <<func-getcustomattribute>> should be used otherwise.

`alarms`::
Array of <<class-alarm, Alarm objects>> of object`s active alarms.

`city`::
Postal address - city.

`comments`::
Object comments.

`country`::
Postal address – country.

`customAttributes`::
Hash map of object custom attributes.

`geolocation`::
Object <<class-geolocation,geographical location>>.

`guid`::
Object GUID as `string`.

`id`::
Object identifier (`uint32`).

`ipAddr`::
Primary IP address (`string`).

`mapImage => ?`::
// TODO: 

`name`::
Object name.

`postcode`::
Postal address – postal code.

`status`::
<<enum-object-status,Object status>>.

`streetAddress`::
Postal address – street.

`type`::
<<enum-object-type,Object type>>.

==== Instance methods

`clearGeoLocation() => void`::
Clears GeoLocation data from the node

`setComments => ?`::
// TODO: 

`setGeoLocation(newLocation)`::
Sets node geographical <<class-geolocation,location>>.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|newLocation|<<class-geolocation>>|
|===

`setMapImage() => ?`::
// TODO: 

`setStatusCalculation() => ?`::
// TODO: 

`setStatusPropagation() => ?`::
// TODO: 
