[.nxsl-class]
[[class-networkmap]]
=== NetworkMap

Class represents Network Map. Extends <<class-netobj>>.

==== Instance attributes

`backgroundColor => Integer`::
Background color in css format <<const-link-colorsource>>.

`backgroundImageId => Integer`::
Background color Id.

`backgroundLatitude => Float`::
Background latitude as floating point number <<class-geolocation>>.

`getBackgroundLongitude => Float`::
Background longitude as floating point number <<class-geolocation>>.

`backgroundZoom => Integer`::
Background zoom.

`defaultLinkColor => Integer`::
Default link color <<const-link-colorsource>>.

`defaultLinkRouting => Integer`::
Default link routing <<const-link-routingalgorithm>>.

`defaultLinkStyle => Integer`::
Default link style <<const-link-style>>.

`defaultLinkWidth => Integer`::
Default link witdh <<class-networkmaplink>>.

`discoveryRadius => Integer`::
Discovery radius <<class-user>>.

`height => Integer`::
Height.

`isUpdateFailed => Boolean`::
Update fail check.

`layout => Integer`::
Layout.

`mapType => Integer`::
Map type.

`objectDisplayMode => Integer`::
Object display mode.

`seedObjects => Array`::
Seed objects

`width => Integer`::
Width.


