[.nxsl-class]
[[class-networkmap]]
=== NetworkMap

Class represents Network Map. Extends <<class-netobj>>.

==== Instance attributes

include::_shared/netobj-attrs.adoc[]

[.attr-list]
--
[[networkmap-backgroundColor]]
backgroundColor => Integer::
Background color in css format <<const-link-colorsource>>.

[[networkmap-backgroundImageId]]
backgroundImageId => Integer::
Image library GUID.

[[networkmap-backgroundLatitude]]
backgroundLatitude => Float::
Background latitude as floating point number <<class-geolocation>>.

[[networkmap-backgroundLongitude]]
backgroundLongitude => Float::
Background longitude as floating point number <<class-geolocation>>.

[[networkmap-backgroundZoom]]
backgroundZoom => Integer::
Background zoom.

[[networkmap-defaultLinkColor]]
defaultLinkColor => Integer::
Default link color <<const-link-colorsource>>.

[[networkmap-defaultLinkRouting]]
defaultLinkRouting => Integer::
Default link routing <<const-link-routingalgorithm>>.

[[networkmap-defaultLinkStyle]]
defaultLinkStyle => Integer::
Default link style <<const-link-style>>.

[[networkmap-defaultLinkWidth]]
defaultLinkWidth => Integer::
Default link witdh <<class-networkmaplink>>.

[[networkmap-discoveryRadius]]
discoveryRadius => Integer::
Discovery radius <<class-user>>.

[[networkmap-height]]
height => Integer::
Height.

[[networkmap-isUpdateFailed]]
isUpdateFailed => Boolean::
Update fail check.

[[networkmap-layout]]
layout => Integer::
Layout.

[[networkmap-mapType]]
mapType => Integer::
Map type.

[[networkmap-objectDisplayMode]]
objectDisplayMode => Integer::
Object display mode.

[[networkmap-seedObjects]]
seedObjects => Array::
Seed objects

[[networkmap-width]]
width => Integer::
Width.
--


