[.nxsl-class]
[[class-networkmap]]
=== NetworkMap

Class represents Network Map. Extends <<class-netobj>>.

==== Instance attributes

include::_shared/netobj-attrs.adoc[]

[.attr-list]
--
[[networkmap-backgroundColor]]
backgroundColor: int::
Background color in css format <<const-link-colorsource>>.

[[networkmap-backgroundImageId]]
backgroundImageId: int::
Image library GUID.

[[networkmap-backgroundLatitude]]
backgroundLatitude => Float::
Background latitude as floating point number <<class-geolocation>>.

[[networkmap-backgroundLongitude]]
backgroundLongitude => Float::
Background longitude as floating point number <<class-geolocation>>.

[[networkmap-backgroundZoom]]
backgroundZoom: int::
Background zoom.

[[networkmap-defaultLinkColor]]
defaultLinkColor: int::
Default link color <<const-link-colorsource>>.

[[networkmap-defaultLinkRouting]]
defaultLinkRouting: int::
Default link routing <<const-link-routingalgorithm>>.

[[networkmap-defaultLinkStyle]]
defaultLinkStyle: int::
Default link style <<const-link-style>>.

[[networkmap-defaultLinkWidth]]
defaultLinkWidth: int::
Default link witdh <<class-networkmaplink>>.

[[networkmap-discoveryRadius]]
discoveryRadius: int::
Discovery radius <<class-user>>.

[[networkmap-height]]
height: int::
Height.

[[networkmap-isUpdateFailed]]
isUpdateFailed: bool::
Update fail check.

[[networkmap-layout]]
layout: int::
Layout.

[[networkmap-mapType]]
mapType: int::
Map type.

[[networkmap-objectDisplayMode]]
objectDisplayMode: int::
Object display mode.

[[networkmap-seedObjects]]
seedObjects : <<class-array,Array>>::
Seed objects

[[networkmap-width]]
width: int::
Width.
--


