[[class-newnode]]
=== NewNode

Represents newly discovered node object. Used by discovery filters.

// TODO: 

==== Instance attributes

`agentVersion`::
NetXMS agent version string, if available.

`ipAddr`::
String representation of IP address.

`isAgent`::
`TRUE` if NetXMS agent is detected on node.

`isBridge`::
`TRUE` if node is a bridge.

`isCDP`::
`TRUE` if node supports CDP (Cisco Discovery Protocol).

`isLLDP`::
`TRUE` if node supports LLDP (Link Layer Discovery Protocol).

`isPrinter`::
`TRUE` if node is a printer.

`isRouter`::
`TRUE` if node is a router (has IP forwarding enabled).

`isSNMP`::
`TRUE` if SNMP agent detected on node.

`isSONMP`::
`TRUE` if node supports SONMP/NDP (Synoptics/Nortel Discovery Protocol).

`netMask`::
Number of bits in IP network mask.

`platformName`::
Platform name reported by NetXMS agent.

`snmpOID`::
SNMP object identifier (value of .1.3.6.1.2.1.1.2.0).

`snmpVersion`::
Detected SNMP version:
  * 0 = SNMP version 1
  * 1 = SNMP version 2c
  * 2 = SNMP version 3

`subnet`::
IP subnet address as string. Example: node with IP address 192.168.2.7 and network mask 255.255.255.0, is in a subnet 192.168.2.0.

`zone => ?`::
// TODO: 

`zoneUIN => ?`::
// TODO: 
