[[class-node]]
=== Node

Represents NetXMS node object. Extends <<class-datacollectiontarget>>.

==== Instance attributes

`agentCertificateSubject => String`::
Subject of certificate issued for agent tunnel on this node.

`agentId => String`::
NetXMS agent unique ID (`string` representation of GUID). Will return all zeroes GUID if agent is not detected on node or does not have unique ID.

`agentVersion`::
NetXMS agent version as `string`.

`bootTime`::
Number of seconds since node start or `0` if unknown.

`bridgeBaseAddress`::
Base address of the switch formatted as 12 character `string` without separators. Value is only valid for bridges and switches. Special value `000000000000` indicates that address is unknown.

`capabilities => Integer`::
Bit mask of <<node-capabilities>>.

`components => String`::
// TODO:

`dependentNodes => ?`::
// TODO: 

`driver`::
Named of selected device-specific SNMP driver.

`flags => Integer`::
Bit mask of <<node-flags>>.

`hasAgentIfXCounters => Boolean`::
`TRUE` if agent supports 64-bit interface counters.

`hasEntityMIB => Boolean`::
`TRUE` if supports ENTITY-MIB.

`hasIfXTable => Boolean`::
`TRUE` if supports ifXTable.

`hasUserAgent => Boolean`::
`TRUE` if has user agent

`hasVLANs => Boolean`::
`TRUE` if VLAN information available.

`hasWinPDH => Boolean`::
`TRUE` if node supports Windows PDH parameters.

`hypervisorInfo => String`::
Additional information about hypervisor for this node.

`hypervisorType => String`::
Hypervisor type as `string` (usually hypervisor vendor or product name, like VMWare or XEN).

`icmpAverageRTT => Integer`::
ICMP average response time for primary address. Will return null if no information.

`icmpLastRTT => Integer`::
ICMP last response time for primary address. Will return null if no information.

`icmpMaxRTT => Integer`::
ICMP maximal response time for primary address. Will return null if no information.

`icmpMinRTT => Integer`::
ICMP minimal response time for primary address. Will return null if no information.

`icmpPacketLoss => Integer`::
ICMP packet loss for primary address. Will return null if no information.

`interfaces => Array`::
Array with <<class-interface>> objects, that are under this node. First object placed at index 0.

`is802_1x => Boolean`::
`TRUE` if node supports 802.1x. Equivalent of `isPAE`.

`isAgent => Boolean`::
`TRUE` if NetXMS agent detected on node

`isBridge => Boolean`::
`TRUE` if node is a bridge

`isCDP => Boolean`::
`TRUE` if node supports CDP (Cisco Discovery Protocol)

`isLLDP => Boolean`::
`TRUE` if node supports LLDP (Link Layer Discovery Protocol)

`isLocalManagement => Boolean`::
`TRUE` if node is a local management server (NetXMS server)

`isLocalMgmt => Boolean`::
`TRUE` if node is a local management server (NetXMS server)

`isNDP => Boolean`::
`TRUE` if node supports OSPF/NDP. Equivalent of `isOSPF`.

`isOSPF => Boolean`::
`TRUE` if node supports OSPF/NDP. Equivalent of `isNDP`.

`isPAE`::
`TRUE` if node supports 802.1x. Equivalent of `is802_1x`.

`isPrinter`::
`TRUE` if node is a printer

`isRouter`::
`TRUE` if node is a router (has IP forwarding enabled)

`isSNMP`::
`TRUE` if SNMP agent detected on node

`isSONMP`::
`TRUE` if node supports SONMP/NDP (Synoptics/Nortel Discovery Protocol)

`isSTP => ?`::
// TODO: 

`isUserAgentInstalled => Boolean`::
`TURE` if user agent is installed.

`isVirtual => ?`::
// TODO: 

`isVRRP => Boolean`
`TURE` if VRRP supported.

`lastAgentCommTime => Integer`::
Unix timestamp of last time when communication with agent was

`nodeSubType => ?`::
// TODO: 

`nodeType => ?`::
// TODO: 

`platformName => String`::
Platform name reported by NetXMS agent

`rack => ?`::
// TODO: 

`rackHeight => ?`::
// TODO: 

`rackId => ?`::
// TODO: 

`rackPosition => ?`::
// TODO: 

`runtimeFlags`::
Bit mask of <<node-runtime-flags>>, `uint32`.

`snmpOID`::
SNMP object identifier (result of `.1.3.6.1.2.1.1.2.0` request)

`snmpSysContact`::
SNMP system contact (result of `.1.3.6.1.2.1.1.4.0` request)

`snmpSysLocation`::
SNMP system location (result of `.1.3.6.1.2.1.1.6.0` request)

`snmpSysName`::
SNMP system name (result of `.1.3.6.1.2.1.1.5.0` request)

`snmpVersion`::
Configured SNMP version:

* 0: SNMP version 1
* 1: SNMP version 2c
* 2: SNMP version 3

`sysDescription`::
System description (value of `System.Uname` for nodes with agents or `.1.3.6.1.2.1.1.1.0` for SNMP nodes)

`vlans => Array`::
Array with object <<class-vlan>> objects (`null` if there are no VLANs)

`zone => <<class-zone>>`::
<<class-zone>> object (`null` if zoning is disabled)

`zoneProxyAssignments => Integer`::
Number of objects where this node is selected as either primary or backup zone proxy (`0` if zoning is disabled or this node is not a zone proxy).

`zoneProxyStatus => Boolean`::
Status of this node as zone proxy (`true` if active).

`zoneUIN => Integer`::
This node zone UIN

==== Instance methods

`void createSNMPTransport(port, context) => <<class-snmp_transport>>`::
Create SNMP transport object of class <<class-snmp_transport>> with communication settings defined on the node. 

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|port|Integer|Optional parameter with port.
|context|String|Optional parameter with context.
|===

`void enableAgent(flag)`::
Enable or disable usage of NetXMS agent for all polls.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If agent usage should be enabled. 
|===

`void enableConfigurationPolling(flag) => void`::
Enable or disable configuration polling for a node

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If configuration polling should be enabled. 
|===

`enableDiscoveryPolling(flag) => void`::
Enable or disable discovery polling.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If discovery polling should be enabled. 
|=== 

`enableIcmp(flag) => void`::
Enable or disable usage of ICMP pings for status polls.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If ICMP pings should be enabled. 
|=== 

`enablePrimaryIPPing(flag) => void`::
Enable or disable usage of ICMP ping for primary IP.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If primary IP ping should be enabled. 
|=== 

`enableRoutingTablePolling(flag) => void`::
Enable or disable routing table polling.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If routing table polls should be enabled. 
|=== 

`enableSnmp(flag) => void`::
Enable or disable usage of SNMP for all polls.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If SNMP communication should be enabled. 
|=== 

`enableStatusPolling(flag) => void`::
Enable or disable status polling for a node.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If status polls should be enabled. 
|=== 

`enableTopologyPolling(flag) => void`::
Enable or disable topology polling.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If topology polls should be enabled. 
|=== 

`executeSSHCommand(command) => void`::
Execute SSH command on node.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|command|String|Command to be executed. 
|=== 

`getInterface(ifIndex) => <<class-interface>>`::
Get interface object by index.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|ifIndex|Integer|Index of interface. 
|=== 

`getInterfaceName(ifIndex) => String`::
Get interface name by index.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|ifIndex|Integer|Index of interface. 
|=== 

`readAgentParameter(name) => String`::
Reads current value of agent metric. 

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|name|String|Parameter name. 
|=== 

`readAgentList(name) => Array`::
Reads current value of agent list metric and returns array of strings.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|name|String|List name. 
|=== 

`readAgentTable(name) => <<class-table>>`::
Reads current value of agent table metric and returns <<class-table>>.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|name|String|Table name. 
|=== 

`readDriverParameter(name) => String`::
Reads current value of driver metric.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|name|String|List name. 
|=== 

==== Constants

[[node-flags]]
[cols="1,4a"]
.Node flags
|===
| Description | Value

|DCF_DISABLE_STATUS_POLL  
|0x00000001 

|DCF_DISABLE_CONF_POLL  
|0x00000002 

|DCF_DISABLE_DATA_COLLECT  
|0x00000004 

|NF_REMOTE_AGENT  
|0x00010000 

|NF_DISABLE_DISCOVERY_POLL 
|0x00020000

|NF_DISABLE_TOPOLOGY_POLL  
|0x00040000 

|NF_DISABLE_SNMP  
|0x00080000 

|NF_DISABLE_NXCP  
|0x00100000 

|NF_DISABLE_ICMP  
|0x00200000 

|NF_FORCE_ENCRYPTION  
|0x00400000 

|NF_DISABLE_ROUTE_POLL  
|0x00800000 

|NF_AGENT_OVER_TUNNEL_ONLY
|0x01000000

|NF_SNMP_SETTINGS_LOCKED  
|0x02000000 

|===

[[node-runtime-flags]]
[cols="1,4a"]
.Node runtime flags
|===
| Description | Value

|DCDF_QUEUED_FOR_STATUS_POLL  
|0x00000001 

|DCDF_QUEUED_FOR_CONFIGURATION_POLL 
|0x00000002

|DCDF_QUEUED_FOR_INSTANCE_POLL  
|0x00000004 

|DCDF_DELETE_IN_PROGRESS  
|0x00000008 

|DCDF_FORCE_STATUS_POLL  
|0x00000010 

|DCDF_FORCE_CONFIGURATION_POLL  
|0x00000020 

|DCDF_CONFIGURATION_POLL_PASSED  
|0x00000040 

|DCDF_CONFIGURATION_POLL_PENDING  
|0x00000080 

|NDF_QUEUED_FOR_TOPOLOGY_POLL  
|0x00010000 

|NDF_QUEUED_FOR_DISCOVERY_POLL  
|0x00020000 

|NDF_QUEUED_FOR_ROUTE_POLL  
|0x00040000 

|NDF_RECHECK_CAPABILITIES  
|0x00080000 

|NDF_NEW_TUNNEL_BIND  
|0x00100000 

|===

[[node-capabilities]]
[cols="1,4a"]
.Node capabilities
|===
| Description | Value

|NC_IS_SNMP  
|0x00000001 

|NC_IS_NATIVE_AGENT  
|0x00000002 

|NC_IS_BRIDGE  
|0x00000004 

|NC_IS_ROUTER  
|0x00000008 

|NC_IS_LOCAL_MGMT  
|0x00000010 

|NC_IS_PRINTER  
|0x00000020 

|NC_IS_OSPF  
|0x00000040 

|NC_IS_CPSNMP. CheckPoint SNMP agent on port 260. 
|0x00000080 

|NC_IS_CDP  
|0x00000100 

|NC_IS_NDP. Supports Nortel (Synoptics/Bay Networks) topology discovery. SONMP is an old name for NDP. 
|0x00000200 

|NC_IS_LLDP. Supports Link Layer Discovery Protocol. 
|0x00000400 

|NC_IS_VRRP. VRRP support. 
|0x00000800 

|NC_HAS_VLANS. VLAN information available. 
|0x00001000 

|NC_IS_8021X. 802.1x support enabled on node. 
|0x00002000 

|NC_IS_STP. Spanning Tree (IEEE 802.1d) enabled on node. 
|0x00004000 

|NC_HAS_ENTITY_MIB. Supports ENTITY-MIB. 
|0x00008000 

|NC_HAS_IFXTABLE. Supports ifXTable. 
|0x00010000 

|NC_HAS_AGENT_IFXCOUNTERS. Agent supports 64-bit interface counters. 
|0x00020000 

|NC_HAS_WINPDH. Node supports Windows PDH parameters. 
|0x00040000 

|NC_IS_WIFI_CONTROLLER. Node is wireless network controller. 
|0x00080000 

|NC_IS_SMCLP. Node supports SMCLP protocol. 
|0x00100000 

|NC_IS_NEW_POLICY_TYPES. Defines if agent is already upgraded to new policy type. 
|0x00200000 

|NC_IS_USER_AGENT_INSTALLED 
|0x00400000

|===
