[[class-node]]
=== Node

Represents NetXMS node object. Extends <<class-datacollectiontarget>>.

==== Instance attributes

`agentCertificateSubject => ?`::
// TODO: 

`agentId => ?`::
// TODO: 

`agentVersion`::
NetXMS agent version as `string`.

`bootTime`::
Number of seconds since node start or `0` if unknown.

`bridgeBaseAddress`::
Base address of the switch formatted as 12 character `string` without separators. Value is only valid for bridges and switches. Special value `000000000000` indicates that address is unknown.

`capabilities => Integer`::
Bit mask of <<node-capabilities>>.

`components => ?`::
// TODO: 

`dependentNodes => ?`::
// TODO: 

`driver`::
Named of selected device-specific SNMP driver.

`flags => Integer`::
Bit mask of <<node-flags>>.

`hasAgentIfXCounters => Boolean`::
`TRUE` if agent supports 64-bit interface counters.

`hasEntityMIB => Boolean`::
`TRUE` if supports ENTITY-MIB.

`hasIfXTable => Boolean`::
`TRUE` if supports ifXTable.

`hasVLANs => Boolean`::
`TRUE` if VLAN information available.

`hasWinPDH => Boolean`::
`TRUE` if node supports Windows PDH parameters.

`hypervisorInfo => ?`::
// TODO: 

`hypervisorType => ?`::
// TODO: 

`is802_1x`::
`TRUE` if node supports 802.1x. Equivalent of `isPAE`.

`isAgent => ?`::
`TRUE` if NetXMS agent detected on node

`isBridge`::
`TRUE` if node is a bridge

`isCDP`::
`TRUE` if node supports CDP (Cisco Discovery Protocol)

`isInMaintenanceMode => ?`::
// TODO: 

`isLLDP`::
`TRUE` if node supports LLDP (Link Layer Discovery Protocol)

`isLocalManagement`::
`TRUE` if node is a local management server (NetXMS server)

`isLocalMgmt`::
`TRUE` if node is a local management server (NetXMS server)

`isNDP => Boolean`::
`TRUE` if node supports OSPF/NDP. Equivalent of `isOSPF`.

`isOSPF => Boolean`::
`TRUE` if node supports OSPF/NDP. Equivalent of `isNDP`.

`isPAE`::
`TRUE` if node supports 802.1x. Equivalent of `is802_1x`.

`isPrinter`::
`TRUE` if node is a printer

`isRouter`::
`TRUE` if node is a router (has IP forwarding enabled)

`isSNMP`::
`TRUE` if SNMP agent detected on node

`isSONMP`::
`TRUE` if node supports SONMP/NDP (Synoptics/Nortel Discovery Protocol)

`isSTP => ?`::
// TODO: 

`isUserAgentInstalled => Boolean`::
`TURE` if user agent is installed.

`isVirtual => ?`::
// TODO: 

`isVRRP => Boolean`
`TURE` if VRRP supported.

`lastAgentCommTime => ?`::
// TODO: 

`nodeSubType => ?`::
// TODO: 

`nodeType => ?`::
// TODO: 

`platformName`::
Platform name reported by NetXMS agent

`rack => ?`::
// TODO: 

`rackHeight => ?`::
// TODO: 

`rackId => ?`::
// TODO: 

`rackPosition => ?`::
// TODO: 

`runtimeFlags`::
Bit mask of <<node-runtime-flags>>, `uint32`.

`snmpOID`::
SNMP object identifier (result of `.1.3.6.1.2.1.1.2.0` request)

`snmpSysContact`::
SNMP system contact (result of `.1.3.6.1.2.1.1.4.0` request)

`snmpSysLocation`::
SNMP system location (result of `.1.3.6.1.2.1.1.6.0` request)

`snmpSysName`::
SNMP system name (result of `.1.3.6.1.2.1.1.5.0` request)

`snmpVersion`::
Configured SNMP version:

* 0: SNMP version 1
* 1: SNMP version 2c
* 2: SNMP version 3

`sysDescription`::
System description (value of `System.Uname` for nodes with agents or `.1.3.6.1.2.1.1.1.0` for SNMP nodes)

`zone`::
<<class-zone>> object (`null` if zoning is disabled)

`zoneProxyAssignments => Integer`::
Number of objects where this node is selected as either primary or backup zone proxy (`0` if zoning is disabled or this node is not a zone proxy).

`zoneProxyStatus => Boolean`::
Status of this node as zone proxy (`true` if active).

`zoneUIN => ?`::
// TODO: 

==== Instance methods

`void enableAgent(boolean flag)`::
Enable or disable usage of NetXMS agent for all polls.

`void enableConfigurationPolling(boolean)`::
Enable or disable configuration polling for a node

`enableDiscoveryPolling() => ?`::
// TODO: 

`enableIcmp(boolean)`::
Enable or disable usage of ICMP pings for status polls

`enableRoutingTablePolling() => ?`::
// TODO: 

`enableSnmp(boolean)`::
Enable or disable usage of SNMP for all polls

`enableStatusPolling`::
Enable or disable status polling for a node

`enableTopologyPolling(boolean)`::
Enable or disable topology polling

==== Constants

[[node-flags]]
[cols="1,4a"]
.Node flags
|===
| Description | Value

|DCF_DISABLE_STATUS_POLL  
|00000001 

|DCF_DISABLE_CONF_POLL  
|00000002 

|DCF_DISABLE_DATA_COLLECT  
|00000004 

|NF_REMOTE_AGENT  
|00010000 

|NF_DISABLE_DISCOVERY_POLL 
|0x00020000

|NF_DISABLE_TOPOLOGY_POLL  
|00040000 

|NF_DISABLE_SNMP  
|00080000 

|NF_DISABLE_NXCP  
|00100000 

|NF_DISABLE_ICMP  
|00200000 

|NF_FORCE_ENCRYPTION  
|00400000 

|NF_DISABLE_ROUTE_POLL  
|00800000 

|NF_AGENT_OVER_TUNNEL_ONLY
|0x01000000

|NF_SNMP_SETTINGS_LOCKED  
|02000000 

|===

[[node-runtime-flags]]
[cols="1,4a"]
.Node runtime flags
|===
| Description | Value

|DCDF_QUEUED_FOR_STATUS_POLL  
|00000001 

|DCDF_QUEUED_FOR_CONFIGURATION_POLL 
|0x00000002

|DCDF_QUEUED_FOR_INSTANCE_POLL  
|00000004 

|DCDF_DELETE_IN_PROGRESS  
|00000008 

|DCDF_FORCE_STATUS_POLL  
|00000010 

|DCDF_FORCE_CONFIGURATION_POLL  
|00000020 

|DCDF_CONFIGURATION_POLL_PASSED  
|00000040 

|DCDF_CONFIGURATION_POLL_PENDING  
|00000080 

|NDF_QUEUED_FOR_TOPOLOGY_POLL  
|00010000 

|NDF_QUEUED_FOR_DISCOVERY_POLL  
|00020000 

|NDF_QUEUED_FOR_ROUTE_POLL  
|00040000 

|NDF_RECHECK_CAPABILITIES  
|00080000 

|NDF_NEW_TUNNEL_BIND  
|00100000 

|===

[[node-capabilities]]
[cols="1,4a"]
.Node runtime flags
|===
| Description | Value

|NC_IS_SNMP  
|00000001 

|NC_IS_NATIVE_AGENT  
|00000002 

|NC_IS_BRIDGE  
|00000004 

|NC_IS_ROUTER  
|00000008 

|NC_IS_LOCAL_MGMT  
|00000010 

|NC_IS_PRINTER  
|00000020 

|NC_IS_OSPF  
|00000040 

|NC_IS_CPSNMP. CheckPoint SNMP agent on port 260. 
|00000080 

|NC_IS_CDP  
|00000100 

|NC_IS_NDP. Supports Nortel (Synoptics/Bay Networks) topology discovery. SONMP is an old name for NDP. 
|00000200 

|NC_IS_LLDP. Supports Link Layer Discovery Protocol. 
|00000400 

|NC_IS_VRRP. VRRP support. 
|00000800 

|NC_HAS_VLANS. VLAN information available. 
|00001000 

|NC_IS_8021X. 802.1x support enabled on node. 
|00002000 

|NC_IS_STP. Spanning Tree (IEEE 802.1d) enabled on node. 
|00004000 

|NC_HAS_ENTITY_MIB. Supports ENTITY-MIB. 
|00008000 

|NC_HAS_IFXTABLE. Supports ifXTable. 
|00010000 

|NC_HAS_AGENT_IFXCOUNTERS. Agent supports 64-bit interface counters. 
|00020000 

|NC_HAS_WINPDH. Node supports Windows PDH parameters. 
|00040000 

|NC_IS_WIFI_CONTROLLER. Node is wireless network controller. 
|00080000 

|NC_IS_SMCLP. Node supports SMCLP protocol. 
|00100000 

|NC_IS_NEW_POLICY_TYPES. Defines if agent is already upgraded to new policy type. 
|00200000 

|NC_IS_USER_AGENT_INSTALLED 
|0x00400000

|===
