[.nxsl-class]
[[class-node]]
=== Node

Represents NetXMS node object. Extends <<class-datacollectiontarget>>.

==== Instance attributes

`agentCertificateMappingData => String`::
Agent certificate mapping data (set in object properties).

`agentCertificateMappingMethod => String`::
Agent certificate mapping method (set in object properties).

`agentCertificateSubject => String`::
Subject of certificate issued for agent tunnel on this node.

`agentId => String`::
NetXMS agent unique ID (`string` representation of GUID). Will return all zeroes GUID if agent is not detected on node or does not have unique ID.

`agentProxy => <<class-node>>`::
Object that is set as agent proxy in object properties or NULL. 

`agentVersion => String`::
NetXMS agent version as `string`.

`bootTime => Integer64`::
Number of seconds since node start or `0` if unknown.

`bridgeBaseAddress => String`::
Base address of the switch formatted as 12 character `string` without separators. Value is only valid for bridges and switches. Special value `000000000000` indicates that address is unknown.

[[class-node-capabilities,Node::capabilities]]
`capabilities => Integer`::
Detected node capabilities ("Have Agent", "Support SNMP", etc.) Bitwise AND of <<node-capabilities>> constants.

`cipDeviceType => Integer`::
EtherNet/IP device type

`cipDeviceTypeAsText => String`::
EtherNet/IP device type as text

`cipExtendedStatus => Integer`::
EtherNet/IP device extended status

`cipExtendedStatusAsText => String`::
EtherNet/IP device extended status as text

`cipStatus => Integer`::
EtherNet/IP device status

`cipStatusAsText => String`::
EtherNet/IP device status as text

`cipState => Integer`::
EtherNet/IP device state

`cipStateAsText => String`::
EtherNet/IP device state as text

`cipVendorCode => Integer`::
EtherNet/IP vendor code in numeric form.

`components => <<class-component>>`::
Entity MIB components of class <<class-component>>.

`dependentNodes => Array`::
Will return array with <<class-node-dependency>> class objects. This array contains all objects that have current node as a proxy or data collection sources.

`driver => String`::
Named of selected device-specific SNMP driver.

`downSince => Integer64`::
UNIX timestamp when node went down.

`effectiveAgentProxy => <<class-node>>`::
Object that is effective agent proxy or NULL. 

`effectiveIcmpProxy => <<class-node>>`::
Object that is effective ICMP proxy or NULL. 

`effectiveSnmpProxy => <<class-node>>`::
Object that is effective SNMP proxy or NULL. 

`flags => Integer`::
Bit mask of <<node-flags>>.

`hasAgentIfXCounters => Boolean`::
`TRUE` if agent supports 64-bit interface counters.

`hasEntityMIB => Boolean`::
`TRUE` if supports ENTITY-MIB.

`hasIfXTable => Boolean`::
`TRUE` if supports ifXTable.

`hasUserAgent => Boolean`::
`TRUE` if has user agent

`hasVLANs => Boolean`::
`TRUE` if VLAN information available.

`hardwareId => String`::
Nodes' unique hardware id

`hasWinPDH => Boolean`::
`TRUE` if node supports Windows PDH parameters.

`hypervisorInfo => String`::
Additional information about hypervisor for this node.

`hypervisorType => String`::
Hypervisor type as `string` (usually hypervisor vendor or product name, like VMWare or XEN).

`icmpAverageRTT => Integer`::
ICMP average response time for primary address. Will return null if no information.

`icmpLastRTT => Integer`::
ICMP last response time for primary address. Will return null if no information.

`icmpMaxRTT => Integer`::
ICMP maximal response time for primary address. Will return null if no information.

`icmpMinRTT => Integer`::
ICMP minimal response time for primary address. Will return null if no information.

`icmpPacketLoss => Integer`::
ICMP packet loss for primary address. Will return null if no information.

`icmpProxy => <<class-node>>`::
Object that is set as ICMP proxy in object properties or NULL. 

`interfaces => Array`::
Array with <<class-interface>> objects, that are under this node. First object placed at index 0.

`is802_1x => Boolean`::
`TRUE` if node supports 802.1x. Equivalent of `isPAE`.

`isAgent => Boolean`::
`TRUE` if NetXMS agent detected on node

`isBridge => Boolean`::
`TRUE` if node is a bridge

`isCDP => Boolean`::
`TRUE` if node supports CDP (Cisco Discovery Protocol)

`isEtherNetIP => Boolean`::
`TRUE` if node supports EtherNet/IP (Industrial Protocol)

`isInMaintenanceMode => Boolean`::
`TRUE` if node is in maintenance mode

`isLLDP => Boolean`::
`TRUE` if node supports LLDP (Link Layer Discovery Protocol)

`isLocalManagement => Boolean`::
`TRUE` if node is a local management server (NetXMS server)

`isLocalMgmt => Boolean`::
`TRUE` if node is a local management server (NetXMS server)

`isNDP => Boolean`::
`TRUE` if node supports OSPF/NDP. Equivalent of `isOSPF`.

`isModbusTCP => Boolean`::
`TRUE` if node supports Modbus TCP

`isOSPF => Boolean`::
`TRUE` if node supports OSPF/NDP. Equivalent of `isNDP`.

`isPAE => Boolean`::
`TRUE` if node supports 802.1x. Equivalent of `is802_1x`.

`isPrinter => Boolean`::
`TRUE` if node is a printer

`isProfiNet => Boolean`::
TRUE` if node supports PROFINET (Process Field Network)

`isRemotelyManaged => Boolean`::
TRUE` if node is remotely managed node

`isRouter => Boolean`::
`TRUE` if node is a router (has IP forwarding enabled)

`isSMCLP => Boolean`::
`TRUE` if node supports SMCLP (Server Management Command Line Protocol)

`isSNMP => Boolean`::
`TRUE` if SNMP agent detected on node

`isSONMP => Boolean`::
`TRUE` if node supports SONMP/NDP (Synoptics/Nortel Discovery Protocol)

`isSTP  => Boolean`::
`TRUE` if node supports STP (Spanning Tree Protocol)

`isUserAgentInstalled => Boolean`::
`TRUE` if user agent is installed.

`isVirtual  => Boolean`::
`TRUE` if node is virtual

`isVRRP => Boolean`::
`TURE` if VRRP supported.

`lastAgentCommTime => Integer`::
Unix timestamp of last time when communication with agent was

`nodeSubType => String`::
Node sub type

[[class-node-types,Node::types]]
`nodeType => Integer`::
Node type <<node-types>>

`platformName => String`::
Platform name reported by NetXMS agent

`physicalContainer => Object`::
Physical container object: Rack <<class-netobj>> or Chassis <<class-chassis>>

`physicalContainerId => Integer`::
Physical container object id (Rack or Chassis)

`primaryHostName => String`::
Primary host name

`productCode => String`::
Hardware system property - product code

`productName => String`::
Hardware system property - product name

`productVersion => String`::
Hardware system property - product version

`rack => <<class-netobj>>`::
Will return Rack object as <<class-netobj>> if node is added in rack

`rackId => Integer`::
Will return Rack id if node is added in rack

`rackHeight => Integer`::
Object height in rack

`rackPosition => Integer`::
Object position in rack

`runtimeFlags => Integer`::
Bit mask of <<node-runtime-flags>>, `uint32`.

`serialNumber => String`::
Serial number from hardware system property

`snmpOID => String`::
SNMP object identifier (result of `.1.3.6.1.2.1.1.2.0` request)

`snmpProxy => <<class-node>>`::
Object that is set as SNMP proxy in object properties or NULL. 

`snmpSysContact => String`::
SNMP system contact (result of `.1.3.6.1.2.1.1.4.0` request)

`snmpSysLocation => String`::
SNMP system location (result of `.1.3.6.1.2.1.1.6.0` request)

`snmpSysName => String`::
SNMP system name (result of `.1.3.6.1.2.1.1.5.0` request)

`snmpVersion => Integer`::
Configured SNMP version:

* 0: SNMP version 1
* 1: SNMP version 2c
* 2: SNMP version 3

`sysDescription => String`::
System description (value of `System.Uname` for nodes with agents or `.1.3.6.1.2.1.1.1.0` for SNMP nodes)

`tunnel => <<class-tunnel>>`::
Tunnel object f this node or NULL if there is no tunnel active and bound to this node. 

`vendor => String`::
Hardware vendor information

`vlans => Array`::
Array with object <<class-vlan>> objects (`null` if there are no VLANs)

`zone => <<class-zone>>`::
<<class-zone>> object (`null` if zoning is disabled)

`zoneProxyAssignments => Integer`::
Number of objects where this node is selected as either primary or backup zone proxy (`0` if zoning is disabled or this node is not a zone proxy).

`zoneProxyStatus => Boolean`::
Status of this node as zone proxy (`true` if active).

`zoneUIN => Integer`::
This node zone UIN

==== Instance methods

`void createSNMPTransport(port, context) => <<class-snmp_transport>>`::
Create SNMP transport object of class <<class-snmp_transport>> with communication settings defined on the node.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|port|Integer|Optional parameter with port.
|context|String|Optional parameter with context.
|===

`void enableAgent(flag)`::
Enable or disable usage of NetXMS agent for all polls.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If agent usage should be enabled.
|===

`void enableConfigurationPolling(flag) => void`::
Enable or disable configuration polling for a node

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If configuration polling should be enabled.
|===

`enableDiscoveryPolling(flag) => void`::
Enable or disable discovery polling.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If discovery polling should be enabled.
|===

`enableEtherNetIP(flag) => void`::
Enable or disable usage of EtherNet/IP for polls.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If EtherNet/IP should be enabled.
|===

`enableIcmp(flag) => void`::
Enable or disable usage of ICMP pings for status polls.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If ICMP pings should be enabled.
|===

`enablePrimaryIPPing(flag) => void`::
Enable or disable usage of ICMP ping for primary IP.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If primary IP ping should be enabled.
|===

`enableRoutingTablePolling(flag) => void`::
Enable or disable routing table polling.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If routing table polls should be enabled.
|===

`enableSnmp(flag) => void`::
Enable or disable usage of SNMP for all polls.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|flag|Boolean|If SNMP communication should be enabled.
|===

`enableStatusPolling(flag) => void`::
Enable or disable status polling for a node.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If status polls should be enabled.
|===

`enableTopologyPolling(flag) => void`::
Enable or disable topology polling.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|flag|Boolean|If topology polls should be enabled.
|===

`executeSSHCommand(command) => void`::
Execute SSH command on node.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|command|String|Command to be executed.
|===

[[class-node-getinterface,Node::getInterface()]]
`getInterface(ifIdentifier) => <<class-interface>>`::
Get interface object by index, MAC address or name. If
name is number method will assume that it is index.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|ifIdentifier|Integer or String|Index, MAC address or name of interface.
|===

.Return
<<class-interface>> object.

.Example
[.source]
....
println $node->getInterface("00:14:22:04:25:37")->name; // Will print "wlp4s0"
println $node->getInterface(3)->name; // Will print "wlp4s0"
println $node->getInterface("wlp4s0")->name; // Will print "wlp4s0"
....

[[class-node-getinterfacebyindex,Node::getInterfaceByIndex()]]
`getInterfaceByIndex(ifIndex) => <<class-interface>>`::
Get interface object by index.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|ifIndex|Integer|Index of interface.
|===

.Return
<<class-interface>> object.

.Example
[.source]
....
println $node->getInterfaceByIndex(3)->name; // Will print "wlp4s0"
....

[[class-node-getinterfacebymacaddress,Node::getInterfaceByMACAddress()]]
`getInterfaceByMACAddress(ifMACAddr) => <<class-interface>>`::
Get interface object by MAC address.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|ifMACAddr|String|MAC address of interface.
|===

.Return
<<class-interface>> object.

.Example
[.source]
....
println $node->getInterfaceByMACAddress("00:14:22:04:25:37")->name; // Will print "wlp4s0"
....

[[class-node-getinterfacebyname,Node::getInterfaceByName()]]
`getInterfaceByName(IfName) => <<class-interface>>`::
Get interface object by name.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|IfName|String|Name of interface.
|===

.Return
<<class-interface>> object.

.Example
[.source]
....
println $node->getInterfaceByName("wlp4s0")->name; // Will print "wlp4s0"
....

`getInterfaceName(ifIndex) => String`::
Get interface name by index.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|ifIndex|Integer|Index of interface.
|===

[[class-node-readagentparameter,Node::readAgentParameter()]]
`readAgentParameter(name) => String`::
Reads current value of agent metric.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|name|String|Parameter name.
|===

[[class-node-readagentlist,Node::readAgentList()]]
`readAgentList(name) => Array`::
Reads current value of agent list metric and returns array of strings.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|List name.
|===

[[class-node-readagenttable,Node::readAgentTable()]]
`readAgentTable(name) => <<class-table>>`::
Reads current value of agent table metric and returns <<class-table>>.

.Parameters
[cols="1,1a,3a" grid="none", frame="none"]
|===
|name|String|Table name.
|===

[[class-node-readdriverparameter,Node::readDriverParameter()]]
`readDriverParameter(name) => String`::
Request driver-specific metric directly from network device driver (e.g. Rital).

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|List name.
|===

[[class-node-readWebServiceList,Node::readWebServiceList()]]
`readWebServiceList(name) => Array`::
Read list from node using web service

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Name is expected in form service:path or service(arguments):path
|===

.Return
Array with string with web service instances

[[class-node-readWebServiceParameter,Node::readWebServiceParameter()]]
`readWebServiceParameter(name) => String`::
Read from node web service parameter

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Name is expected in form service:path or service(arguments):path
|===

.Return
String with result read from web service

==== Constants

[[node-flags]]
[cols="1,4a"]
.Node flags
|===
| Description | Value

|DCF_DISABLE_STATUS_POLL
|0x00000001

|DCF_DISABLE_CONF_POLL
|0x00000002

|DCF_DISABLE_DATA_COLLECT
|0x00000004

|DCF_LOCATION_CHANGE_EVENT
|0x00000008

|NF_EXTERNAL_GATEWAY
|0x00010000

|NF_DISABLE_DISCOVERY_POLL
|0x00020000

|NF_DISABLE_TOPOLOGY_POLL
|0x00040000

|NF_DISABLE_SNMP
|0x00080000

|NF_DISABLE_NXCP
|0x00100000

|NF_DISABLE_ICMP
|0x00200000

|NF_FORCE_ENCRYPTION
|0x00400000

|NF_DISABLE_ROUTE_POLL
|0x00800000

|NF_AGENT_OVER_TUNNEL_ONLY
|0x01000000

|NF_SNMP_SETTINGS_LOCKED
|0x02000000

|NF_PING_PRIMARY_IP
|0x04000000

|NF_DISABLE_ETHERNET_IP
|0x08000000

|NF_DISABLE_PERF_COUNT
|0x10000000

|===

[[node-runtime-flags]]
[cols="1,4a"]
.Node runtime flags
|===
| Description | Value

|DCDF_QUEUED_FOR_STATUS_POLL
|0x00000001

|DCDF_QUEUED_FOR_CONFIGURATION_POLL
|0x00000002

|DCDF_QUEUED_FOR_INSTANCE_POLL
|0x00000004

|DCDF_DELETE_IN_PROGRESS
|0x00000008

|DCDF_FORCE_STATUS_POLL
|0x00000010

|DCDF_FORCE_CONFIGURATION_POLL
|0x00000020

|DCDF_CONFIGURATION_POLL_PASSED
|0x00000040

|DCDF_CONFIGURATION_POLL_PENDING
|0x00000080

|NDF_QUEUED_FOR_TOPOLOGY_POLL
|0x00010000

|NDF_QUEUED_FOR_DISCOVERY_POLL
|0x00020000

|NDF_QUEUED_FOR_ROUTE_POLL
|0x00040000

|NDF_RECHECK_CAPABILITIES
|0x00080000

|NDF_NEW_TUNNEL_BIND
|0x00100000

|===

[[node-capabilities]]
[cols="1,5a"]
.Node capability flags
|===
| Value | Description

|0x00000001
|Node supports SNMP

|0x00000002
|NetXMS agent detected on the node

|0x00000004
|Node is network bridge

|0x00000008
|Node is IP router

|0x00000010
|Node is management server (NetXMS server itself)

|0x00000020
|Node is printer

|0x00000040
|Node supports OSPF

|0x00000080
|CheckPoint SNMP agent detected on port 260

|0x00000100
|CDP supported

|0x00000200
|NDP(SONMP) support detected on the node (Nortel/Synoptics/Bay Networks) topology discovery)

|0x00000400
|Node supports LLDP

|0x00000800
|Node supportes VRRP

|0x00001000
|VLAN information available on the node

|0x00002000
|802.1x support detected

|0x00004000
|Spanning Tree (IEEE 802.1d) enabled on node

|0x00008000
|Node supports ENTITY-MIB

|0x00010000
|Node supports ifXTable

|0x00020000
|Agent supports 64-bit interface counters

|0x00040000
|Node supports Windows PDH parameters

|0x00080000
|Node is wireless network controller

|0x00100000
|Node supports SMCLP protocol

|0x00200000
|Running agent is upgraded to new policy type

|0x00400000
|User (support) agent is installed

|===


[[node-types]]
[cols="1,5a"]
.Node types
|===
| Value | Description

|0
|Unknown

|1
|Physical

|2
|Virtual

|0
|Controller

|0
|Container

|===
