[.nxsl-class]
[[class-nodedependency]]
=== NodeDependency

Detailed information about dependent nodes, usually accessible via instance attribute `dependentNodes` in class <<class-node>>.

==== Instance attributes

`id => Integer`::
Node id

`isAgentProxy => Boolean`::
Node is an agent proxy. Helper function for accesing specific bit of `type` field.

`isDataCollectionSource => Boolean`::
Node is a data collection source for another node. Helper function for accesing specific bit of `type` field.

`isICMPProxy => Boolean`::
Node is an ICMP proxy for another node. Helper function for accesing specific bit of `type` field.

`isSNMPProxy => Boolean`::
Node is a SNMP proxy for another node. Helper function for accesing specific bit of `type` field.

`type => Integer`::
Type of of the dependencty this object represent. This field is a bitmask, flags are documented at <<enum-dependency-type>>.

==== Constants

[[enum-dependency-type]]
[cols="1,5a"]
.Type bitmask
|===
| Value | Description

|0x01
|Agent proxy  

|0x02
|SNMP proxy   

|0x04
|ICMP proxy   

|0x08
|Data collection source   

|===
