[.nxsl-class]
[[class-room]]
=== Room

[.version-added]
Added in version 7.0

Object represents room - physical space within a <<class-facility>> with floor plan on which racks can be placed. Room outline is a polygon with vertex coordinates in millimetres; for rectangular rooms it is a rectangle with origin in the top-left corner. Extends <<class-datacollectiontarget>>.

==== Instance attributes

include::_shared/netobj-attrs.adoc[]

include::_shared/datacollectiontarget-attrs.adoc[]

[.attr-list]
--
[[room-area]]
area: double::
Floor area in square metres calculated from the outline. `0` if outline has fewer than three vertices.

[[room-autoBindScript]]
autoBindScript: <<class-string,String>>::
Source of the script for automatic binding.

[[room-backgroundImage]]
backgroundImage: <<class-string,String>>::
UUID of the floor plan background image from image library. `NULL` if no background image is set.

[[room-gridLabels]]
gridLabels: int::
Floor tile grid label scheme as one of the <<room-grid-labels,numeric values>>.

[[room-gridLabelsName]]
gridLabelsName: <<class-string,String>>::
Symbolic name of floor tile grid label scheme (`NONE`, `LETTERS_NUMBERS`, or `NUMBERS_NUMBERS`).

[[room-gridOriginX]]
gridOriginX: int::
X coordinate of floor tile grid origin in millimetres.

[[room-gridOriginY]]
gridOriginY: int::
Y coordinate of floor tile grid origin in millimetres.

[[room-gridTileSize]]
gridTileSize: int::
Floor tile size in millimetres. `0` if floor tile grid is not defined.

[[room-height]]
height: int::
Room height in millimetres. `0` if undeclared.

[[room-isAutoBindEnabled]]
isAutoBindEnabled: bool::
Indicate if automatic binding is enabled.

[[room-isAutoUnbindEnabled]]
isAutoUnbindEnabled: bool::
Indicate if automatic unbinding is enabled.

[[room-outline]]
outline: array::
Room outline as array of polygon vertices in order. Each vertex is a hash map with keys `x` and `y` holding coordinates in millimetres.
+
[.source]
....
foreach(p : $object.outline)
{
   println(p["x"] .. "," .. p["y"]);
}
....

[[room-roomType]]
roomType: int::
Room type as one of the <<room-types,numeric values>>.

[[room-roomTypeName]]
roomTypeName: <<class-string,String>>::
Symbolic name of room type (`COMPUTER_ROOM`, `ELECTRICAL`, `MECHANICAL`, `TELECOM`, or `OTHER`).
--

==== Instance methods

include::_shared/netobj-methods.adoc[]

include::_shared/datacollectiontarget-methods.adoc[]

[.method-list]
--
[[room-createNode]]
createNode(name, primaryHostName, zoneUIN) => <<class-node>>::
Create new node under current object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Node name if second options is set or primary host name or IP address.
|primaryHostName|String|Optional. Primary host name or IP address.
|zoneUIN|Integer|Optional. New node's zone UIN.
|===
+
.Return
Newly created node of <<class-node>> class or NULL if failed to create.

[[room-createRack]]
createRack(name, height, width, depth) => <<class-rack>>::
Create new rack under current object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New rack's name
|height|Integer|Optional. Rack height in units. `42` if omitted or not positive.
|width|Integer|Optional. External cabinet width in millimetres. `600` if omitted or not positive.
|depth|Integer|Optional. External cabinet depth in millimetres. `1000` if omitted or not positive.
|===
+
.Return
Newly created rack of <<class-rack>> class or NULL if failed to create.

[[room-createSensor]]
createSensor(name, deviceClass, gateway, modbusUnitId) => <<class-sensor>>::
Create new sensor under current object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Sensor name
|deviceClass|Integer|Sensor device class, one of the following <<const-sensor-device-class,values>>. Optional, ``SensorDeviceClass::Other`` if omitted.
|gateway|<<class-netobj>>|Gateway used for communication sensor. Optional.
|modbusUnitId|Integer|MODBUS Unit ID. Optional.
|===
+
.Return
Newly created sensor of <<class-sensor>> class or NULL if failed to create.

[[room-setAutoBindMode]]
setAutoBindMode(enableBind, enableUnbind): void::
Set automatic bind mode for the object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|enableBind|Boolean|Script should be used for automatic binding.
|enableUnbind|Boolean|Script should be used for automatic unbinding.
|===

[[room-setAutoBindScript]]
setAutoBindScript(script): void::
Update automatic binding script source.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|script|String|Script source.
|===
--

==== Constants

[[room-types]]
[cols="1,1,4a"]
.Room types
|===
| Value | Name | Description

| 0 | COMPUTER_ROOM | Computer room (server hall)
| 1 | ELECTRICAL | Electrical room
| 2 | MECHANICAL | Mechanical room
| 3 | TELECOM | Telecommunications room
| 4 | OTHER | Other
|===

[[room-grid-labels]]
[cols="1,1,4a"]
.Floor tile grid label schemes
|===
| Value | Name | Description

| 0 | NONE | Grid tiles are not labelled
| 1 | LETTERS_NUMBERS | Columns labelled with letters, rows with numbers
| 2 | NUMBERS_NUMBERS | Both columns and rows labelled with numbers
|===
