[.nxsl-class]
[[class-serviceroot]]
=== ServiceRoot

Class represents Service Root container

==== Instance methods

[[class-serviceRoot-createCollector,ServiceRoot::createCollector()]]
`createCollector(name) => <<class-collector>>`::
Create new collector under current object

[NOTE]
This function is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New collector's name
|===

.Return

Newly created collector of <<class-collector>> class.

[[class-serviceRoot-createContainer,ServiceRoot::createContainer()]]
`createContainer(name) => <<class-container>>`::
Create new container under current object

[NOTE]
This function is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New container's name
|===

.Return

Newly created container of <<class-container>> class.


[[class-serviceRoot-createNode,ServiceRoot::createNode()]]
`createNode(name, primaryHostName, zoneUIN) => <<class-node>>`::
Create new node under current object.

[NOTE]
This function is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Node name if second options is set or primary host name or IP address.
|primaryHostName|String|Optional. Primary host name or IP address.
|zoneUIN|Integer|Optional. New node's zone UIN.
|===

.Return

Newly created node of <<class-node>> class or NULL if failed to create