[.nxsl-class]
[[class-serviceroot]]
=== ServiceRoot

Class represents Service Root container

==== Instance methods

[.method-list]
--
[[serviceroot-createCollector]]
createCollector(name) => <<class-collector>>::
Create new collector under current object
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New collector's name
|===
+
.Return
Newly created collector of <<class-collector>> class.

[[serviceroot-createContainer]]
createContainer(name) => <<class-container>>::
Create new container under current object
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New container's name
|===
+
.Return
Newly created container of <<class-container>> class.

[[serviceroot-createFacility]]
createFacility(name) => <<class-facility>>::
+
[.version-added]
Added in version 7.0
+
Create new facility under current object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New facility's name
|===
+
.Return
Newly created facility of <<class-facility>> class or NULL if failed to create.

[[serviceroot-createNode]]
createNode(name, primaryHostName, zoneUIN) => <<class-node>>::
Create new node under current object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Node name if second options is set or primary host name or IP address.
|primaryHostName|String|Optional. Primary host name or IP address.
|zoneUIN|Integer|Optional. New node's zone UIN.
|===
+
.Return
Newly created node of <<class-node>> class or NULL if failed to create

[[serviceroot-createRack]]
createRack(name, height) => <<class-rack>>::
+
[.version-added]
Added in version 7.0
+
Create new rack under current object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|New rack's name
|height|Integer|Optional. Rack height in units. `0` if omitted.
|===
+
.Return
Newly created rack of <<class-rack>> class or NULL if failed to create.

[[serviceroot-createSensor]]
createSensor(name, deviceClass, gateway, modbusUnitId) => <<class-sensor>>::
Create new sensor under current object.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Sensor name
|deviceClass|Integer|Sensor device class, one of the following <<const-sensor-device-class,values>>. Optional, ``SensorDeviceClass::Other`` if omitted.
|gateway|<<class-netobj>>|Gateway used for communication sensor. Optional.
|modbusUnitId|Integer|MODBUS Unit ID. Optional.
|===
+
.Return
Newly created sensor of <<class-sensor>> class or NULL if failed to create
--
