[.nxsl-class]
[[class-serviceroot]]
=== ServiceRoot

Class represents Service Root container

==== Instance methods

`createCollector(name) => <<class-collector>>`::
Create new collector under current container.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Collector name
|===

.Return

Newly created collector of <<class-collector>> class.


`createContainer(name) => <<class-container>>`::
Create new container under Service Root container.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Container name
|===

.Return

Newly created container of <<class-container>> class.


[[class-serviceroot-createNode,ServiceRoot::createNode()]]
`createNode(name, primaryHostName, zoneUIN) => <<class-node>>`::
Create new node under the ServiceRoot.

[NOTE]
This function is disabled by default and should be explicitly enabled by setting configuration parameter "NXSL.EnableContainerFunctions".

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Node name if second options is set or primary host name or IP address.
|primaryHostName|String|Optional. Primary host name or IP address.
|zoneUIN|Integer|Optional. New node's zone UIN.
|===

.Return

Newly created node of <<class-node>> class or NULL if failed to create