[.nxsl-class]
[[class-snmptransport]]
=== SNMPTransport

Represents SNMP Transport functionality. Objects of this class are typically
obtained from nodes that support SNMP. Objects of this class used to access SNMP
data form node.

==== Instance attributes

[.attr-list]
--
[[snmptransport-snmpVersion]]
snmpVersion: <<class-string,String>>::
SNMP version used by the transport. Can be "1", "2c" or "3"
--

==== Instance methods

[.method-list]
--
[[snmptransport-get]]
get(oid) => <<class-snmpvarbind>>::
Get the object value from specific node with SNMP GET request. The node and all SNMP communication details defined by SNMP transport. Returns <<class-snmpvarbind>> object. Will return null on failure.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|oid|String|SNMP object id. Can be given with or without leading dot.
|===

[[snmptransport-getValue]]
getValue(oid): <<class-string,String>>::
Get the object value from specific node with SNMP GET request. The node and all SNMP communication details defined by SNMP transport. This function is similar to SNMPGet but returns string instead of an SNMPVarBind object. Will return null on failure.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|oid|String|SNMP object id. Can be given with or without leading dot.
|===
+
[.source]
....
println($node.createSNMPTransport()?.getValue("1.3.6.1.2.1.1.2.0")); // Will print e.g. 1.3.6.1.4.1.14988.1
....

[[snmptransport-getValues]]
getValues(array): <<class-string,String>>::
Get object values from specific node with SNMP GET request. Request will contain all values that are provided in array. The node and all SNMP communication details defined by SNMP transport.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|array|Array|Array with SNMP object ids to get
|===
+
.Return
Array with resulting strings for each array

[[snmptransport-set]]
set(oid, value, dataType): bool::
Assign a specific value to the given SNMP object for the node. The node and all SNMP communication details defined by SNMP transport. Will return TRUE on success, FALSE in case of failure.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|oid|String|SNMP object id. Can be given with or without leading dot.
|value|String|Value to assign to oid.
|dataType|String|<<snmp-data-types,SNMP data type>> (optional).
|===

[[snmptransport-walk]]
walk(oid) : <<class-array,Array>>::
Get an array of the <<class-snmpvarbind>> from specific node with SNMP WALK request. The node and all SNMP communication details defined by SNMP transport. Will return null on failure.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|oid|String|SNMP object id. Can be given with or without leading dot.
|===
--

==== Constants

[[snmp-data-types]]
[cols="2,4a"]
.SNMP data types
|===
| Description | Value

|Integer.
|INTEGER

|Same as INTEGER.
|INT

|Octet string.
|STRING

|Object id.
|OID

|IP address.
|IPADDR

|Same as IPADDR.
|IP ADDRESS

|32-bit counter.
|COUNTER32

|32-bit unsigned integer.
|GAUGE32

|Timeticks.
|TIMETICKS

|64-bit counter.
|COUNTER64

|32-bit unsigned integer.
|UINTEGER32

|Same as UINTEGER32.
|UINT32

|===
