[.nxsl-class]
[[class-snmp_transport]]
=== SNMP_Transport

Represents SNMP Transport functionality. Objects of this class are typically obtained from nodes that support SNMP. Objects of this class used to access <<func-group-snmp,SNMP functions>> of nodes.

==== Instance attributes

`snmpVersion`::
SNMP version used by the transport. Can be "1", "2c" or "3"

==== Instance methods

`get(oid) => <<class-snmp_varbind>>`::
Get the object value from specific node with SNMP GET request. The node and all SNMP communication details defined by SNMP transport. Will return null on failure.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|oid|String|SNMP object id.
|===

`getValue(oid) => String`::
Get the object value from specific node with SNMP GET request. The node and all SNMP communication details defined by SNMP transport. This function is similar to SNMPGet but returns string instead of an SNMP_VarBind object. Will return null on failure.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|oid|String|SNMP object id.
|===

`set(oid, value, dataType) => Boolean`::
Assign a specific value to the given SNMP object for the node. The node and all SNMP communication details defined by SNMP transport. Will return TRUE on success, FALSE in case of failure.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|oid|String|SNMP object id.
|value|String|Value to assign to oid.
|dataType|String|<<snmp-data-types,SNMP data type>> (optional).
|===

`walk(oid) => Array`::
Get an array of the <<class-snmp_varbind>> from specific node with SNMP WALK request. The node and all SNMP communication details defined by SNMP transport. Will return null on failure.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|oid|String|SNMP object id.
|===

==== Constants

[[snmp-data-types]]
[cols="1,4a"]
.SNMP data types
|===
| Description | Value

|Integer.  
|INTEGER 

|Same as INTEGER.  
|INT 

|Octet string.  
|STRING 

|Object id.  
|OID 

|IP address. 
|IPADDR

|Same as IPADDR.
|IP ADDRESS 

|32-bit counter.  
|COUNTER32 

|32-bit unsigned integer.  
|GAUGE32 

|Timeticks.  
|TIMETICKS 

|64-bit counter.  
|COUNTER64 

|32-bit unsigned integer.  
|UINTEGER32 

|Same as UINTEGER32.
|UINT32

|===
