[.nxsl-class]
[[class-table]]
=== Table

Represents table object (usually it's value of table DCI).

==== Instance attributes

`columnCount => Number`::
Number of columns.

`columns => Array<TableColumn>`::
Array of <<class-tablecolumn,column definitions>>.

`instanceColumns => Array<TableColumn>`::
Array of <<class-tablecolumn,column definitions>> including only columns marked as instance columns. 

`instanceColumnIndexes => Array<Integer>`::
Array with indexes of columns marked as instance columns. 

`rowCount => Numbers`::
Number of rows.

`rows => Array<TableRow>`::
Array of rows with data.

`title => String`::
Title of table.

==== Instance methods

`addColumn(name, [type], [displayName], [isInstance]) => Integer`::

Adds column to table

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|name|String|Column name
|type|Integer|<<const-dci-datatype,Data type>>, optional parameter. Default is String
|displayName|String|Column display name
|isInstance|Boolean|`True` if column is instance column
|===

.Return 

Column index

`addRow() => Integer`::

Adds row to table

.Return 

Row index

`deleteColumn(columnId) => void`::

Delete column

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|columnId|Integer|Column index
|===

`deleteRow(rowId) => void`::

Delete row

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|rowId|Integer|Row index
|===

`findRowByInstance(instance, instance2, ...) => <<class-tablerow>>`::

Finds row by instance

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|instance|String|Instance string
|instance2|String|Optional. If instance is composed of several columns, these can be supplied as additional parameters. 
|===

.Return 
<<class-tablerow, Table row>> that corresponds to provided instance

`findRowIndexByInstance(instance, instance2, ...) => Integer`::

Finds row index by instance

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|instance|String|Instance string
|instance2|String|Optional. If instance is composed of several columns, these can be supplied as additional parameters. 
|===

.Return 
Table row index corresponds to provided instance

`get(rowId, columnId) => String`::

Get cell value by row and column id

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|rowId|Integer|Row index
|columnId|Integer|Column index
|===

.Return 

Cell value as string

`getColumnIndex(columnName) => Integer`::

Get column index by column name

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|columnName|String|Column name 
|===

.Return 

Column name

`getColumnName(columnId) => String`::

Get column name by column index

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|columnName|Integer|Column name 
|===

.Return 

Column index

`set(rowId, columnId, value) => void`::

Set column value by row and column index

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|rowId|Integer|Row index
|columnId|Integer|Column index
|value|String|New value
|===

.Return 

Column index 

==== Constructors

`Table()`::
Creates new Table object.

