[.nxsl-class]
[[class-template]]
=== Template

Object represents template. Extends <<class-netobj>>.

==== Instance attributes

include::_shared/netobj-attrs.adoc[]

`autoApplyScript => String`::
Source of the script for automatic binding.

`isAutoApplyEnabled => Boolean`::
Indicate if automatic binding is enabled.

`isAutoRemoveEnabled => Boolean`::
Indicate if automatic unbinding is enabled.

`version => Integer`::
Template version

==== Instance methods

`applyTo(object) => void`::
Apply teplate on object

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|Object|Object this template to be applied on
|===


`removeFrom(object) => void`::
emplate form object

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|Object|Object this template to be removed form
|===


`setAutoApplyMode(enableBind, enableUnbind) => void`::
Set automatic bind mode for the container.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|enableBind|Boolean|Script should be used for automatic binding.
|enableUnbind|Boolean|Script should be used for automatic unbinding.
|===


`setAutoApplyScript(script) => void`::
Update automatic binding script source.

.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|script|String|Script content.
|===
