[.nxsl-class]
[[class-template]]
=== Template

Object represents template. Extends <<class-netobj>>.

==== Instance attributes

[.attr-list]
--
include::_shared/netobj-attrs.adoc[]

[[template-autoApplyScript]]
autoApplyScript: <<class-string,String>>::
Source of the script for automatic binding.

[[template-exclusionGroup]]
exclusionGroup: <<class-string,String>>::
Name of the exclusion group this template belongs to, or empty string if not set. Templates in the same exclusion group cannot be applied to the same object at the same time: applying one of them removes the other.
+
[.version-added]
Added in version 6.1

[[template-isAutoApplyEnabled]]
isAutoApplyEnabled: bool::
Indicate if automatic binding is enabled.

[[template-isAutoRemoveEnabled]]
isAutoRemoveEnabled: bool::
Indicate if automatic unbinding is enabled.

[[template-version]]
version: int::
Template version
--

==== Instance methods

[.method-list]
--
[[template-applyTo]]
applyTo(object): void::
Apply template on object
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|Object|Object this template to be applied on
|===

[[template-removeFrom]]
removeFrom(object): void::
Remove template from object
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|object|Object|Object this template to be removed from
|===

[[template-setAutoApplyMode]]
setAutoApplyMode(enableBind, enableUnbind): void::
Set automatic bind mode for the container.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|enableBind|Boolean|Script should be used for automatic binding.
|enableUnbind|Boolean|Script should be used for automatic unbinding.
|===

[[template-setAutoApplyScript]]
setAutoApplyScript(script): void::
Update automatic binding script source.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|script|String|Script content.
|===
--
