[.nxsl-class]
[[class-tunnel]]
=== Tunnel

Object contains information about tunnel.

==== Instance attributes

[.attr-list]
--
[[tunnel-address]]
address => InetAddress::
<<class-inetaddress>> class object with address of the node that opened this tunnel

[[tunnel-agentBuildTag]]
agentBuildTag => String::
Agent build tag

[[tunnel-agentId]]
agentId => String::
Agent ID of the agent that opened the tunnel

[[tunnel-agentVersion]]
agentVersion => String::
Agent version of the node that opened the tunnel

[[tunnel-certificateExpirationTime]]
certificateExpirationTime => Integer::
UNIX timestamp with current certificate expiration day

[[tunnel-guid]]
guid => String::
Tunnel GUID

[[tunnel-hostname]]
hostname => String::
Hostname of the node that opened the tunnel

[[tunnel-hardwareId]]
hardwareId => String::
Hardware ID of the node that opened the tunnel

[[tunnel-id]]
id => Integer::
Tunnel id

[[tunnel-isAgentProxy]]
isAgentProxy => Boolean::
`TRUE` if agent proxy is enabled on the agent that opened the tunnel

[[tunnel-isBound]]
isBound => Boolean::
`TRUE` if tunnel is bound

[[tunnel-isSnmpProxy]]
isSnmpProxy => Boolean::
`TRUE` if SNMP proxy is enabled on the agent that opened the tunnel

[[tunnel-isSnmpTrapProxy]]
isSnmpTrapProxy => Boolean::
`TRUE` if SNMP trap proxy is enabled on the agent that opened the tunnel

[[tunnel-isUserAgentInstalled]]
isUserAgentInstalled => Boolean::
`TRUE` if user agent is installed on the agent that opened the tunnel

[[tunnel-macAddresses]]
macAddresses => Array::
Array with MAC addresses as Strings

[[tunnel-platformName]]
platformName => String::
Platform name of the node that opened the tunnel

[[tunnel-startTime]]
startTime => Integer::
UNIX timestamp with tunnel start time

[[tunnel-serialNumber]]
serialNumber => String::
Serial number

[[tunnel-systemInfo]]
systemInfo => String::
System information of the node that opened the tunnel

[[tunnel-systemName]]
systemName => String::
System name of the node that opened the tunnel

[[tunnel-zoneUIN]]
zoneUIN => Integer::
Node's zone UIN if set in agent's configuration file
--

==== Instance methods

[.method-list]
--
[[tunnel-bind]]
bind(node) => Integer::
Bind the tunnel to a specified node.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|node|<<class-node>>|Node object to bind the tunnel to
|===
+
.Return
Return code (0 on success).
--
