[.nxsl-class]
[[class-tunnel]]
=== Tunnel

Object contains information about tunnel.

==== Instance attributes

[.attr-list]
--
[[tunnel-address]]
address => InetAddress::
<<class-inetaddress>> class object with address of the node that opened this tunnel

[[tunnel-agentBuildTag]]
agentBuildTag: <<class-string,String>>::
Agent build tag

[[tunnel-agentId]]
agentId: <<class-string,String>>::
Agent ID of the agent that opened the tunnel

[[tunnel-agentVersion]]
agentVersion: <<class-string,String>>::
Agent version of the node that opened the tunnel

[[tunnel-certificateExpirationTime]]
certificateExpirationTime: int::
UNIX timestamp with current certificate expiration day

[[tunnel-guid]]
guid: <<class-string,String>>::
Tunnel GUID

[[tunnel-hostname]]
hostname: <<class-string,String>>::
Hostname of the node that opened the tunnel

[[tunnel-hardwareId]]
hardwareId: <<class-string,String>>::
Hardware ID of the node that opened the tunnel

[[tunnel-id]]
id: int::
Tunnel id

[[tunnel-isAgentProxy]]
isAgentProxy: bool::
`TRUE` if agent proxy is enabled on the agent that opened the tunnel

[[tunnel-isBound]]
isBound: bool::
`TRUE` if tunnel is bound

[[tunnel-isSnmpProxy]]
isSnmpProxy: bool::
`TRUE` if SNMP proxy is enabled on the agent that opened the tunnel

[[tunnel-isSnmpTrapProxy]]
isSnmpTrapProxy: bool::
`TRUE` if SNMP trap proxy is enabled on the agent that opened the tunnel

[[tunnel-isUserAgentInstalled]]
isUserAgentInstalled: bool::
`TRUE` if user agent is installed on the agent that opened the tunnel

[[tunnel-macAddresses]]
macAddresses : <<class-array,Array>>::
Array with MAC addresses as Strings

[[tunnel-platformName]]
platformName: <<class-string,String>>::
Platform name of the node that opened the tunnel

[[tunnel-startTime]]
startTime: int::
UNIX timestamp with tunnel start time

[[tunnel-serialNumber]]
serialNumber: <<class-string,String>>::
Serial number

[[tunnel-systemInfo]]
systemInfo: <<class-string,String>>::
System information of the node that opened the tunnel

[[tunnel-systemName]]
systemName: <<class-string,String>>::
System name of the node that opened the tunnel

[[tunnel-zoneUIN]]
zoneUIN: int::
Node's zone UIN if set in agent's configuration file
--

==== Instance methods

[.method-list]
--
[[tunnel-bind]]
bind(node): int::
Bind the tunnel to a specified node.
+
.Parameters
[cols="1,1,3a" grid="none", frame="none"]
|===
|node|<<class-node>>|Node object to bind the tunnel to
|===
+
.Return
Return code (0 on success).
--
