[.nxsl-class]
[[class-user]]
=== User

Object represent user object and extends <<class-userdbobject>>.

==== Instance attributes

[.attr-list]
--
[[user-authMethod]]
authMethod: int::
<<enum-auth-methods,Authentication method>>.

[[user-certMappingData]]
certMappingData: <<class-string,String>>::
Data that will be used to mpa certificate

[[user-certMappingMethod]]
certMappingMethod: int::
<<enum-mapping-methods,Certificate mapping methods>>.

[[user-disabledUntil]]
disabledUntil: <<class-string,String>>::
UNIX timestamp with date until this user is disabled

[[user-email]]
email: <<class-string,String>>::
Email set in user properties

[[user-fullName]]
fullName: <<class-string,String>>::
User full name

[[user-graceLogins]]
graceLogins: int::
Grace login count

[[user-is2FAExempt]]
is2FAExempt: bool::
`TRUE` if user is exempt from two-factor authentication enforcement.
+
[.version-added]
Added in version 6.1

[[user-phoneNumber]]
phoneNumber: <<class-string,String>>::
Phone number set in user properties

[[user-lastLogin]]
lastLogin: int::
UNIX timestamp with last user's login time

[[user-twoFAGraceLogins]]
twoFAGraceLogins: int::
Number of remaining logins allowed without two-factor authentication while two-factor authentication enforcement is active and the user has not configured a second factor yet. Initial value is set by server configuration parameter `Server.Security.2FA.GraceLoginCount`.
+
[.version-added]
Added in version 6.1
--

==== Constants

[[enum-auth-methods]]
[cols="1,4a"]
.Status propagation types
|===
| Code | Description

| 0
| Password

| 1
| Radius

| 2
| Certificate

| 3
| Certificate or password

| 4
| Certificate or radius

|===


[[enum-mapping-methods]]
[cols="1,4a"]
.Status propagation types
|===
| Code | Description

| 0
| Subject

| 1
| Public key

| 2
| CN

|===
