[.nxsl-function]
[[func-instance]]
== Instance()

****
[IMPORTANT]
====
*Deprecated in 5.0.*

Instead of using this function, just return an array with the following values:

1. instance (`{instance}` in DCIs)
2. instance name (`{instance-name}` in DCIs, optional)
3. related object (optional)

Unlike previous versions, `true` is not required as the first value in the array, since presence of the array itself is enough to accept the instance. However, old scripts with four values will still work.
====
****

[source,c]
----
Instance(name, displayName, object) : <<class-array,Array>>
----

This is helper function for instance filter script. It can be used to return accepted item.
This function has named parameters.

.Parameters
[cols="1,1,3" grid="none", frame="none"]
|===
|name|String|Instance name ({instance})
|displayName|String|Instance display name ({instance-name})
|object|<<class-netobj>>|Related object
|===

.Return
Array, where the first value is `true`, the second is `name`, the third is `displayName` and the forth is `object`.

[.source]
....
return Instance(displayName: GetInterfaceName($node, $1), object: GetInterfaceObject($node, $1), name: $1); //This will return correctly formatted array to accept instance
....
